// Copyright 2026 Pigs Can Fly Labs LLC
// SPDX-License-Identifier: Apache-2.0
//
// The app ships under one identity, `ca.pigscanfly.liberatedbread`, and every
// platform has its own place to spell it. They drift silently: nothing fails to
// build when one of them disagrees, the wrong id just ends up baked into an
// artifact — a second app entry on a device, a Home Assistant registration that
// no longer matches the app it came from, or an iOS provisioning profile that
// stops matching the bundle.
//
// `flutter create` is the usual source of drift. It derives ids from
// `<org>.<project>`, which for this project would be
// `ca.pigscanfly.liberated_bread_mobile` — close enough to look right in a
// diff, and wrong. Re-scaffolding a platform (documented in the README) is
// exactly when that happens, so these assertions exist to catch it.

import 'package:flutter_test/flutter_test.dart';

import 'platform_config_reader.dart';

/// The one true application identity. Deliberately a literal rather than a
/// value read from any of the files under test — a test that derives the
/// expectation from one of the things it is checking cannot detect drift.
const String appId = 'ca.pigscanfly.liberatedbread';

/// Dart package name from pubspec.yaml. Distinct from [appId] on purpose:
/// pub names cannot contain dots, so this is snake_case and is NOT expected to
/// match the reverse-DNS id.
const String dartPackageName = 'liberated_bread_mobile';

void main() {
  group('every platform agrees on the application id', () {
    test('Android applicationId and namespace', () {
      final gradle = readRepoFile(
        'android/app/build.gradle',
        consequence: 'It defines the Android application id.',
      );
      for (final key in const ['applicationId', 'namespace']) {
        final match =
            RegExp('$key\\s*=\\s*"([^"]+)"').firstMatch(gradle)?.group(1);
        expect(
          match,
          appId,
          reason: 'android/app/build.gradle $key is "$match", expected '
              '"$appId". A mismatched applicationId ships as a different app: '
              'it installs alongside the real one instead of upgrading it, and '
              'it invalidates the Home Assistant device registration keyed on '
              'AppConstants.haAppId.',
        );
      }
    });

    test('iOS bundle identifier in every build configuration', () {
      final pbxproj = readRepoFile(
        'ios/Runner.xcodeproj/project.pbxproj',
        consequence: 'It defines the iOS bundle identifier.',
      );
      // RunnerTests legitimately uses the `.RunnerTests` suffix; the app target
      // must be exactly the app id, in all of Debug/Release/Profile. Checking
      // only one configuration is how a Release-only mismatch survives.
      final ids = RegExp(r'PRODUCT_BUNDLE_IDENTIFIER = ([^;]+);')
          .allMatches(pbxproj)
          .map((m) => m.group(1)!.trim())
          .where((id) => !id.endsWith('.RunnerTests'))
          .toSet();
      expect(
        ids,
        {appId},
        reason: 'ios app-target PRODUCT_BUNDLE_IDENTIFIER values are $ids, '
            'expected every one to be "$appId". A build configuration that '
            'disagrees stops matching the provisioning profile, so ad-hoc and '
            'App Store builds fail to sign for that configuration only.',
      );
    });

    test('macOS bundle identifier', () {
      final xcconfig = readRepoFile(
        'macos/Runner/Configs/AppInfo.xcconfig',
        consequence: 'It defines the macOS bundle identifier.',
      );
      final id = RegExp(r'PRODUCT_BUNDLE_IDENTIFIER\s*=\s*(\S+)')
          .firstMatch(xcconfig)
          ?.group(1);
      expect(id, appId,
          reason: 'macos AppInfo.xcconfig PRODUCT_BUNDLE_IDENTIFIER is "$id", '
              'expected "$appId".');
    });

    test('Linux APPLICATION_ID', () {
      // The most drift-prone of the lot: linux/ is generated by
      // `flutter create --platforms=linux`, which writes <org>.<project> here.
      final cmake = readRepoFile(
        'linux/CMakeLists.txt',
        consequence: 'It defines the Linux desktop application id.',
      );
      final id = RegExp(r'set\(APPLICATION_ID\s+"([^"]+)"\)')
          .firstMatch(cmake)
          ?.group(1);
      expect(
        id,
        appId,
        reason: 'linux/CMakeLists.txt APPLICATION_ID is "$id", expected '
            '"$appId". flutter create derives this from <org>.<project> '
            '(ca.pigscanfly.$dartPackageName), so re-scaffolding the Linux '
            'target silently reintroduces the wrong value.',
      );
    });

    test('AppConstants.haAppId matches the platform ids', () {
      // Sent to Home Assistant as the app identity; if it drifts from the
      // platform ids, HA registers the app under a name that no longer
      // corresponds to the installed artifact.
      final constants = readRepoFile(
        'lib/core/constants.dart',
        consequence: 'It defines the Home Assistant app id.',
      );
      final id =
          RegExp("haAppId\\s*=\\s*'([^']+)'").firstMatch(constants)?.group(1);
      expect(id, appId,
          reason: 'AppConstants.haAppId is "$id", expected "$appId".');
    });
  });

  group('the cargokit plugin module carries no template identity', () {
    // rust_builder/ is vendored from cargokit and shipped with placeholder
    // names. They are invisible at runtime, which is why they survived the
    // rebrand — but they end up in the built AAR's metadata, and a stale name
    // here is a reliable signal that a cargokit re-vendor clobbered local
    // edits (which would also revert the load-bearing CMake plugin-name fix in
    // rust_builder/linux and rust_builder/windows).
    const staleNames = [
      'rust_lib_liberated_bread_mobile',
      'com.flutter_rust_bridge',
    ];

    const pluginFiles = [
      'rust_builder/android/build.gradle',
      'rust_builder/android/src/main/AndroidManifest.xml',
      'rust_builder/android/settings.gradle',
      'rust_builder/linux/CMakeLists.txt',
      'rust_builder/windows/CMakeLists.txt',
    ];

    for (final path in pluginFiles) {
      test('$path has no cargokit placeholder name', () {
        final content = readRepoFile(
          path,
          consequence: 'It is part of the cargokit native-build wiring.',
        );
        for (final stale in staleNames) {
          expect(
            content,
            isNot(contains(stale)),
            reason: '$path still contains the cargokit template name '
                '"$stale". Everything under rust_builder/ should identify as '
                'ca.pigscanfly.liberatedbread.rust (Android) or '
                'liberated_bread_core (the plugin name). If this appeared '
                'suddenly, cargokit was probably re-vendored over the local '
                'fixes — check rust_builder/linux/CMakeLists.txt still exports '
                'liberated_bread_core_bundled_libraries, or the Rust library '
                'will stop being bundled into desktop builds.',
          );
        }
      });
    }

    test(
        'the Linux/Windows CMake bundled-libraries variable matches the '
        'plugin name', () {
      // Flutter's generated_plugins.cmake looks up
      // ${plugin_name}_bundled_libraries, where plugin_name comes from
      // rust_builder/pubspec.yaml. A mismatch does not fail the build — it
      // silently omits libliberated_bread_core.so from the bundle, and the app
      // dies on its first FFI call instead.
      final pubspec = readRepoFile(
        'rust_builder/pubspec.yaml',
        consequence: 'It names the native-build plugin.',
      );
      final pluginName = RegExp(r'^name:\s*(\S+)', multiLine: true)
          .firstMatch(pubspec)
          ?.group(1);
      expect(pluginName, isNotNull,
          reason: 'Could not read the plugin name from '
              'rust_builder/pubspec.yaml.');

      for (final path in const [
        'rust_builder/linux/CMakeLists.txt',
        'rust_builder/windows/CMakeLists.txt',
      ]) {
        final cmake = readRepoFile(path,
            consequence: 'It bundles the Rust library into desktop builds.');
        expect(
          cmake,
          contains('${pluginName}_bundled_libraries'),
          reason: '$path must export '
              '"${pluginName}_bundled_libraries" to match the plugin name in '
              'rust_builder/pubspec.yaml. Flutter reads exactly that variable; '
              'any other name means the Rust library is never bundled and the '
              'desktop app crashes on its first FFI call, with a completely '
              'green build.',
        );
      }
    });
  });
}
