// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/device_api.dart';
import 'api/mock_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'spec/types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, double> dco_decode_Map_String_f_64_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ImageUploadDto dco_decode_box_autoadd_image_upload_dto(dynamic raw);

  @protected
  ImageWriteDto dco_decode_box_autoadd_image_write_dto(dynamic raw);

  @protected
  MacPrefixDto dco_decode_box_autoadd_mac_prefix_dto(dynamic raw);

  @protected
  NetworkDeviceDto dco_decode_box_autoadd_network_device_dto(dynamic raw);

  @protected
  NetworkReadingDto dco_decode_box_autoadd_network_reading_dto(dynamic raw);

  @protected
  PanelResolutionDto dco_decode_box_autoadd_panel_resolution_dto(dynamic raw);

  @protected
  QuerySourceDto dco_decode_box_autoadd_query_source_dto(dynamic raw);

  @protected
  ScannedDeviceDto dco_decode_box_autoadd_scanned_device_dto(dynamic raw);

  @protected
  SecurityAdvisoryDto dco_decode_box_autoadd_security_advisory_dto(dynamic raw);

  @protected
  StoredUploadDto dco_decode_box_autoadd_stored_upload_dto(dynamic raw);

  @protected
  StoredUploadEventDto dco_decode_box_autoadd_stored_upload_event_dto(
      dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CharacteristicDto dco_decode_characteristic_dto(dynamic raw);

  @protected
  CommandDto dco_decode_command_dto(dynamic raw);

  @protected
  DecodedValueDto dco_decode_decoded_value_dto(dynamic raw);

  @protected
  DeviceSpecDto dco_decode_device_spec_dto(dynamic raw);

  @protected
  EffectEntryDto dco_decode_effect_entry_dto(dynamic raw);

  @protected
  EntityActionDto dco_decode_entity_action_dto(dynamic raw);

  @protected
  EntityDto dco_decode_entity_dto(dynamic raw);

  @protected
  EntityWriteDto dco_decode_entity_write_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormatFieldDto dco_decode_format_field_dto(dynamic raw);

  @protected
  HttpRequestDto dco_decode_http_request_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageUploadDto dco_decode_image_upload_dto(dynamic raw);

  @protected
  ImageWriteDto dco_decode_image_write_dto(dynamic raw);

  @protected
  ImageWritePlanDto dco_decode_image_write_plan_dto(dynamic raw);

  @protected
  KasaRequestDto dco_decode_kasa_request_dto(dynamic raw);

  @protected
  LifxAccessPointDto dco_decode_lifx_access_point_dto(dynamic raw);

  @protected
  LifxServiceDto dco_decode_lifx_service_dto(dynamic raw);

  @protected
  LifxStateDto dco_decode_lifx_state_dto(dynamic raw);

  @protected
  LifxZoneColorDto dco_decode_lifx_zone_color_dto(dynamic raw);

  @protected
  LifxZonesDto dco_decode_lifx_zones_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CharacteristicDto> dco_decode_list_characteristic_dto(dynamic raw);

  @protected
  List<CommandDto> dco_decode_list_command_dto(dynamic raw);

  @protected
  List<DecodedValueDto> dco_decode_list_decoded_value_dto(dynamic raw);

  @protected
  List<DeviceSpecDto> dco_decode_list_device_spec_dto(dynamic raw);

  @protected
  List<EffectEntryDto> dco_decode_list_effect_entry_dto(dynamic raw);

  @protected
  List<EntityActionDto> dco_decode_list_entity_action_dto(dynamic raw);

  @protected
  List<EntityDto> dco_decode_list_entity_dto(dynamic raw);

  @protected
  List<FormatFieldDto> dco_decode_list_format_field_dto(dynamic raw);

  @protected
  List<ImageWriteDto> dco_decode_list_image_write_dto(dynamic raw);

  @protected
  List<LifxZoneColorDto> dco_decode_list_lifx_zone_color_dto(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MacPrefixDto> dco_decode_list_mac_prefix_dto(dynamic raw);

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw);

  @protected
  List<NetworkActionDto> dco_decode_list_network_action_dto(dynamic raw);

  @protected
  List<NetworkEntityDto> dco_decode_list_network_entity_dto(dynamic raw);

  @protected
  List<NetworkInstanceDto> dco_decode_list_network_instance_dto(dynamic raw);

  @protected
  List<NetworkOptionDto> dco_decode_list_network_option_dto(dynamic raw);

  @protected
  List<NetworkReadBackDto> dco_decode_list_network_read_back_dto(dynamic raw);

  @protected
  List<NetworkRoleReadingDto> dco_decode_list_network_role_reading_dto(
      dynamic raw);

  @protected
  List<NetworkSourceParamDto> dco_decode_list_network_source_param_dto(
      dynamic raw);

  @protected
  List<ParameterDto> dco_decode_list_parameter_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileCharacteristicDto> dco_decode_list_profile_characteristic_dto(
      dynamic raw);

  @protected
  List<ProfileInfoDto> dco_decode_list_profile_info_dto(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(int, Uint8List)> dco_decode_list_record_u_16_list_prim_u_8_strict(
      dynamic raw);

  @protected
  List<ScanMatch> dco_decode_list_scan_match(dynamic raw);

  @protected
  List<ServiceDto> dco_decode_list_service_dto(dynamic raw);

  @protected
  List<SoapRequestDto> dco_decode_list_soap_request_dto(dynamic raw);

  @protected
  List<SoftApProfileDto> dco_decode_list_soft_ap_profile_dto(dynamic raw);

  @protected
  List<SpecIdentityDto> dco_decode_list_spec_identity_dto(dynamic raw);

  @protected
  List<WemoAccessPointDto> dco_decode_list_wemo_access_point_dto(dynamic raw);

  @protected
  MacPrefixConfidence dco_decode_mac_prefix_confidence(dynamic raw);

  @protected
  MacPrefixDto dco_decode_mac_prefix_dto(dynamic raw);

  @protected
  MatchConfidence dco_decode_match_confidence(dynamic raw);

  @protected
  MatchResult dco_decode_match_result(dynamic raw);

  @protected
  NetworkActionDto dco_decode_network_action_dto(dynamic raw);

  @protected
  NetworkDeviceDto dco_decode_network_device_dto(dynamic raw);

  @protected
  NetworkEntityDto dco_decode_network_entity_dto(dynamic raw);

  @protected
  NetworkInstanceDto dco_decode_network_instance_dto(dynamic raw);

  @protected
  NetworkOptionDto dco_decode_network_option_dto(dynamic raw);

  @protected
  NetworkReadBackDto dco_decode_network_read_back_dto(dynamic raw);

  @protected
  NetworkReadingDto dco_decode_network_reading_dto(dynamic raw);

  @protected
  NetworkReadingKind dco_decode_network_reading_kind(dynamic raw);

  @protected
  NetworkRoleReadingDto dco_decode_network_role_reading_dto(dynamic raw);

  @protected
  NetworkSourceParamDto dco_decode_network_source_param_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ImageUploadDto? dco_decode_opt_box_autoadd_image_upload_dto(dynamic raw);

  @protected
  ImageWriteDto? dco_decode_opt_box_autoadd_image_write_dto(dynamic raw);

  @protected
  MacPrefixDto? dco_decode_opt_box_autoadd_mac_prefix_dto(dynamic raw);

  @protected
  NetworkReadingDto? dco_decode_opt_box_autoadd_network_reading_dto(
      dynamic raw);

  @protected
  PanelResolutionDto? dco_decode_opt_box_autoadd_panel_resolution_dto(
      dynamic raw);

  @protected
  QuerySourceDto? dco_decode_opt_box_autoadd_query_source_dto(dynamic raw);

  @protected
  SecurityAdvisoryDto? dco_decode_opt_box_autoadd_security_advisory_dto(
      dynamic raw);

  @protected
  StoredUploadDto? dco_decode_opt_box_autoadd_stored_upload_dto(dynamic raw);

  @protected
  StoredUploadEventDto? dco_decode_opt_box_autoadd_stored_upload_event_dto(
      dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Int64List? dco_decode_opt_list_prim_i_64_strict(dynamic raw);

  @protected
  PanelResolutionDto dco_decode_panel_resolution_dto(dynamic raw);

  @protected
  ParameterDto dco_decode_parameter_dto(dynamic raw);

  @protected
  PlaylistWritesDto dco_decode_playlist_writes_dto(dynamic raw);

  @protected
  ProfileCharacteristicDto dco_decode_profile_characteristic_dto(dynamic raw);

  @protected
  ProfileInfoDto dco_decode_profile_info_dto(dynamic raw);

  @protected
  QuerySourceDto dco_decode_query_source_dto(dynamic raw);

  @protected
  RabbitAirRequestDto dco_decode_rabbit_air_request_dto(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (int, Uint8List) dco_decode_record_u_16_list_prim_u_8_strict(dynamic raw);

  @protected
  ScanMatch dco_decode_scan_match(dynamic raw);

  @protected
  ScannedDeviceDto dco_decode_scanned_device_dto(dynamic raw);

  @protected
  SecurityAdvisoryDto dco_decode_security_advisory_dto(dynamic raw);

  @protected
  ServiceDto dco_decode_service_dto(dynamic raw);

  @protected
  SoapRequestDto dco_decode_soap_request_dto(dynamic raw);

  @protected
  SoftApProfileDto dco_decode_soft_ap_profile_dto(dynamic raw);

  @protected
  SpecIdentityDto dco_decode_spec_identity_dto(dynamic raw);

  @protected
  StoredPlayDto dco_decode_stored_play_dto(dynamic raw);

  @protected
  StoredUploadDto dco_decode_stored_upload_dto(dynamic raw);

  @protected
  StoredUploadEventDto dco_decode_stored_upload_event_dto(dynamic raw);

  @protected
  StoredUploadEventKind dco_decode_stored_upload_event_kind(dynamic raw);

  @protected
  StoredUploadPlanDto dco_decode_stored_upload_plan_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WemoAccessPointDto dco_decode_wemo_access_point_dto(dynamic raw);

  @protected
  WemoJoinStatus dco_decode_wemo_join_status(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  Map<String, double> sse_decode_Map_String_f_64_None(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto sse_decode_box_autoadd_image_upload_dto(
      SseDeserializer deserializer);

  @protected
  ImageWriteDto sse_decode_box_autoadd_image_write_dto(
      SseDeserializer deserializer);

  @protected
  MacPrefixDto sse_decode_box_autoadd_mac_prefix_dto(
      SseDeserializer deserializer);

  @protected
  NetworkDeviceDto sse_decode_box_autoadd_network_device_dto(
      SseDeserializer deserializer);

  @protected
  NetworkReadingDto sse_decode_box_autoadd_network_reading_dto(
      SseDeserializer deserializer);

  @protected
  PanelResolutionDto sse_decode_box_autoadd_panel_resolution_dto(
      SseDeserializer deserializer);

  @protected
  QuerySourceDto sse_decode_box_autoadd_query_source_dto(
      SseDeserializer deserializer);

  @protected
  ScannedDeviceDto sse_decode_box_autoadd_scanned_device_dto(
      SseDeserializer deserializer);

  @protected
  SecurityAdvisoryDto sse_decode_box_autoadd_security_advisory_dto(
      SseDeserializer deserializer);

  @protected
  StoredUploadDto sse_decode_box_autoadd_stored_upload_dto(
      SseDeserializer deserializer);

  @protected
  StoredUploadEventDto sse_decode_box_autoadd_stored_upload_event_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CharacteristicDto sse_decode_characteristic_dto(SseDeserializer deserializer);

  @protected
  CommandDto sse_decode_command_dto(SseDeserializer deserializer);

  @protected
  DecodedValueDto sse_decode_decoded_value_dto(SseDeserializer deserializer);

  @protected
  DeviceSpecDto sse_decode_device_spec_dto(SseDeserializer deserializer);

  @protected
  EffectEntryDto sse_decode_effect_entry_dto(SseDeserializer deserializer);

  @protected
  EntityActionDto sse_decode_entity_action_dto(SseDeserializer deserializer);

  @protected
  EntityDto sse_decode_entity_dto(SseDeserializer deserializer);

  @protected
  EntityWriteDto sse_decode_entity_write_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormatFieldDto sse_decode_format_field_dto(SseDeserializer deserializer);

  @protected
  HttpRequestDto sse_decode_http_request_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto sse_decode_image_upload_dto(SseDeserializer deserializer);

  @protected
  ImageWriteDto sse_decode_image_write_dto(SseDeserializer deserializer);

  @protected
  ImageWritePlanDto sse_decode_image_write_plan_dto(
      SseDeserializer deserializer);

  @protected
  KasaRequestDto sse_decode_kasa_request_dto(SseDeserializer deserializer);

  @protected
  LifxAccessPointDto sse_decode_lifx_access_point_dto(
      SseDeserializer deserializer);

  @protected
  LifxServiceDto sse_decode_lifx_service_dto(SseDeserializer deserializer);

  @protected
  LifxStateDto sse_decode_lifx_state_dto(SseDeserializer deserializer);

  @protected
  LifxZoneColorDto sse_decode_lifx_zone_color_dto(SseDeserializer deserializer);

  @protected
  LifxZonesDto sse_decode_lifx_zones_dto(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CharacteristicDto> sse_decode_list_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  List<CommandDto> sse_decode_list_command_dto(SseDeserializer deserializer);

  @protected
  List<DecodedValueDto> sse_decode_list_decoded_value_dto(
      SseDeserializer deserializer);

  @protected
  List<DeviceSpecDto> sse_decode_list_device_spec_dto(
      SseDeserializer deserializer);

  @protected
  List<EffectEntryDto> sse_decode_list_effect_entry_dto(
      SseDeserializer deserializer);

  @protected
  List<EntityActionDto> sse_decode_list_entity_action_dto(
      SseDeserializer deserializer);

  @protected
  List<EntityDto> sse_decode_list_entity_dto(SseDeserializer deserializer);

  @protected
  List<FormatFieldDto> sse_decode_list_format_field_dto(
      SseDeserializer deserializer);

  @protected
  List<ImageWriteDto> sse_decode_list_image_write_dto(
      SseDeserializer deserializer);

  @protected
  List<LifxZoneColorDto> sse_decode_list_lifx_zone_color_dto(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<MacPrefixDto> sse_decode_list_mac_prefix_dto(
      SseDeserializer deserializer);

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer);

  @protected
  List<NetworkActionDto> sse_decode_list_network_action_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkEntityDto> sse_decode_list_network_entity_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkInstanceDto> sse_decode_list_network_instance_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkOptionDto> sse_decode_list_network_option_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkReadBackDto> sse_decode_list_network_read_back_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkRoleReadingDto> sse_decode_list_network_role_reading_dto(
      SseDeserializer deserializer);

  @protected
  List<NetworkSourceParamDto> sse_decode_list_network_source_param_dto(
      SseDeserializer deserializer);

  @protected
  List<ParameterDto> sse_decode_list_parameter_dto(
      SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileCharacteristicDto> sse_decode_list_profile_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  List<ProfileInfoDto> sse_decode_list_profile_info_dto(
      SseDeserializer deserializer);

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
      SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<(int, Uint8List)> sse_decode_list_record_u_16_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<ScanMatch> sse_decode_list_scan_match(SseDeserializer deserializer);

  @protected
  List<ServiceDto> sse_decode_list_service_dto(SseDeserializer deserializer);

  @protected
  List<SoapRequestDto> sse_decode_list_soap_request_dto(
      SseDeserializer deserializer);

  @protected
  List<SoftApProfileDto> sse_decode_list_soft_ap_profile_dto(
      SseDeserializer deserializer);

  @protected
  List<SpecIdentityDto> sse_decode_list_spec_identity_dto(
      SseDeserializer deserializer);

  @protected
  List<WemoAccessPointDto> sse_decode_list_wemo_access_point_dto(
      SseDeserializer deserializer);

  @protected
  MacPrefixConfidence sse_decode_mac_prefix_confidence(
      SseDeserializer deserializer);

  @protected
  MacPrefixDto sse_decode_mac_prefix_dto(SseDeserializer deserializer);

  @protected
  MatchConfidence sse_decode_match_confidence(SseDeserializer deserializer);

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer);

  @protected
  NetworkActionDto sse_decode_network_action_dto(SseDeserializer deserializer);

  @protected
  NetworkDeviceDto sse_decode_network_device_dto(SseDeserializer deserializer);

  @protected
  NetworkEntityDto sse_decode_network_entity_dto(SseDeserializer deserializer);

  @protected
  NetworkInstanceDto sse_decode_network_instance_dto(
      SseDeserializer deserializer);

  @protected
  NetworkOptionDto sse_decode_network_option_dto(SseDeserializer deserializer);

  @protected
  NetworkReadBackDto sse_decode_network_read_back_dto(
      SseDeserializer deserializer);

  @protected
  NetworkReadingDto sse_decode_network_reading_dto(
      SseDeserializer deserializer);

  @protected
  NetworkReadingKind sse_decode_network_reading_kind(
      SseDeserializer deserializer);

  @protected
  NetworkRoleReadingDto sse_decode_network_role_reading_dto(
      SseDeserializer deserializer);

  @protected
  NetworkSourceParamDto sse_decode_network_source_param_dto(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto? sse_decode_opt_box_autoadd_image_upload_dto(
      SseDeserializer deserializer);

  @protected
  ImageWriteDto? sse_decode_opt_box_autoadd_image_write_dto(
      SseDeserializer deserializer);

  @protected
  MacPrefixDto? sse_decode_opt_box_autoadd_mac_prefix_dto(
      SseDeserializer deserializer);

  @protected
  NetworkReadingDto? sse_decode_opt_box_autoadd_network_reading_dto(
      SseDeserializer deserializer);

  @protected
  PanelResolutionDto? sse_decode_opt_box_autoadd_panel_resolution_dto(
      SseDeserializer deserializer);

  @protected
  QuerySourceDto? sse_decode_opt_box_autoadd_query_source_dto(
      SseDeserializer deserializer);

  @protected
  SecurityAdvisoryDto? sse_decode_opt_box_autoadd_security_advisory_dto(
      SseDeserializer deserializer);

  @protected
  StoredUploadDto? sse_decode_opt_box_autoadd_stored_upload_dto(
      SseDeserializer deserializer);

  @protected
  StoredUploadEventDto? sse_decode_opt_box_autoadd_stored_upload_event_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Int64List? sse_decode_opt_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  PanelResolutionDto sse_decode_panel_resolution_dto(
      SseDeserializer deserializer);

  @protected
  ParameterDto sse_decode_parameter_dto(SseDeserializer deserializer);

  @protected
  PlaylistWritesDto sse_decode_playlist_writes_dto(
      SseDeserializer deserializer);

  @protected
  ProfileCharacteristicDto sse_decode_profile_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  ProfileInfoDto sse_decode_profile_info_dto(SseDeserializer deserializer);

  @protected
  QuerySourceDto sse_decode_query_source_dto(SseDeserializer deserializer);

  @protected
  RabbitAirRequestDto sse_decode_rabbit_air_request_dto(
      SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  (int, Uint8List) sse_decode_record_u_16_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  ScanMatch sse_decode_scan_match(SseDeserializer deserializer);

  @protected
  ScannedDeviceDto sse_decode_scanned_device_dto(SseDeserializer deserializer);

  @protected
  SecurityAdvisoryDto sse_decode_security_advisory_dto(
      SseDeserializer deserializer);

  @protected
  ServiceDto sse_decode_service_dto(SseDeserializer deserializer);

  @protected
  SoapRequestDto sse_decode_soap_request_dto(SseDeserializer deserializer);

  @protected
  SoftApProfileDto sse_decode_soft_ap_profile_dto(SseDeserializer deserializer);

  @protected
  SpecIdentityDto sse_decode_spec_identity_dto(SseDeserializer deserializer);

  @protected
  StoredPlayDto sse_decode_stored_play_dto(SseDeserializer deserializer);

  @protected
  StoredUploadDto sse_decode_stored_upload_dto(SseDeserializer deserializer);

  @protected
  StoredUploadEventDto sse_decode_stored_upload_event_dto(
      SseDeserializer deserializer);

  @protected
  StoredUploadEventKind sse_decode_stored_upload_event_kind(
      SseDeserializer deserializer);

  @protected
  StoredUploadPlanDto sse_decode_stored_upload_plan_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WemoAccessPointDto sse_decode_wemo_access_point_dto(
      SseDeserializer deserializer);

  @protected
  WemoJoinStatus sse_decode_wemo_join_status(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_f_64_None(
      Map<String, double> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_image_write_dto(
      ImageWriteDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mac_prefix_dto(
      MacPrefixDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_network_device_dto(
      NetworkDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_network_reading_dto(
      NetworkReadingDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_panel_resolution_dto(
      PanelResolutionDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_query_source_dto(
      QuerySourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_scanned_device_dto(
      ScannedDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_security_advisory_dto(
      SecurityAdvisoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stored_upload_dto(
      StoredUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_stored_upload_event_dto(
      StoredUploadEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_characteristic_dto(
      CharacteristicDto self, SseSerializer serializer);

  @protected
  void sse_encode_command_dto(CommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_decoded_value_dto(
      DecodedValueDto self, SseSerializer serializer);

  @protected
  void sse_encode_device_spec_dto(DeviceSpecDto self, SseSerializer serializer);

  @protected
  void sse_encode_effect_entry_dto(
      EffectEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_action_dto(
      EntityActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_dto(EntityDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_write_dto(
      EntityWriteDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_format_field_dto(
      FormatFieldDto self, SseSerializer serializer);

  @protected
  void sse_encode_http_request_dto(
      HttpRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_image_write_dto(ImageWriteDto self, SseSerializer serializer);

  @protected
  void sse_encode_image_write_plan_dto(
      ImageWritePlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_kasa_request_dto(
      KasaRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_lifx_access_point_dto(
      LifxAccessPointDto self, SseSerializer serializer);

  @protected
  void sse_encode_lifx_service_dto(
      LifxServiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_lifx_state_dto(LifxStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_lifx_zone_color_dto(
      LifxZoneColorDto self, SseSerializer serializer);

  @protected
  void sse_encode_lifx_zones_dto(LifxZonesDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_characteristic_dto(
      List<CharacteristicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_command_dto(
      List<CommandDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_decoded_value_dto(
      List<DecodedValueDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_device_spec_dto(
      List<DeviceSpecDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_effect_entry_dto(
      List<EffectEntryDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_action_dto(
      List<EntityActionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_dto(
      List<EntityDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_format_field_dto(
      List<FormatFieldDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_image_write_dto(
      List<ImageWriteDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_lifx_zone_color_dto(
      List<LifxZoneColorDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mac_prefix_dto(
      List<MacPrefixDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_match_result(
      List<MatchResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_action_dto(
      List<NetworkActionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_entity_dto(
      List<NetworkEntityDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_instance_dto(
      List<NetworkInstanceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_option_dto(
      List<NetworkOptionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_read_back_dto(
      List<NetworkReadBackDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_role_reading_dto(
      List<NetworkRoleReadingDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_network_source_param_dto(
      List<NetworkSourceParamDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_parameter_dto(
      List<ParameterDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_16_strict(
      Uint16List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_profile_characteristic_dto(
      List<ProfileCharacteristicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_profile_info_dto(
      List<ProfileInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_f_64(
      List<(String, double)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_u_16_list_prim_u_8_strict(
      List<(int, Uint8List)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_scan_match(
      List<ScanMatch> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_dto(
      List<ServiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_soap_request_dto(
      List<SoapRequestDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_soft_ap_profile_dto(
      List<SoftApProfileDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_spec_identity_dto(
      List<SpecIdentityDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_wemo_access_point_dto(
      List<WemoAccessPointDto> self, SseSerializer serializer);

  @protected
  void sse_encode_mac_prefix_confidence(
      MacPrefixConfidence self, SseSerializer serializer);

  @protected
  void sse_encode_mac_prefix_dto(MacPrefixDto self, SseSerializer serializer);

  @protected
  void sse_encode_match_confidence(
      MatchConfidence self, SseSerializer serializer);

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_network_action_dto(
      NetworkActionDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_device_dto(
      NetworkDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_entity_dto(
      NetworkEntityDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_instance_dto(
      NetworkInstanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_option_dto(
      NetworkOptionDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_read_back_dto(
      NetworkReadBackDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_reading_dto(
      NetworkReadingDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_reading_kind(
      NetworkReadingKind self, SseSerializer serializer);

  @protected
  void sse_encode_network_role_reading_dto(
      NetworkRoleReadingDto self, SseSerializer serializer);

  @protected
  void sse_encode_network_source_param_dto(
      NetworkSourceParamDto self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_upload_dto(
      ImageUploadDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_write_dto(
      ImageWriteDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mac_prefix_dto(
      MacPrefixDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_network_reading_dto(
      NetworkReadingDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_panel_resolution_dto(
      PanelResolutionDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_query_source_dto(
      QuerySourceDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_security_advisory_dto(
      SecurityAdvisoryDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stored_upload_dto(
      StoredUploadDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_stored_upload_event_dto(
      StoredUploadEventDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_i_64_strict(
      Int64List? self, SseSerializer serializer);

  @protected
  void sse_encode_panel_resolution_dto(
      PanelResolutionDto self, SseSerializer serializer);

  @protected
  void sse_encode_parameter_dto(ParameterDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_writes_dto(
      PlaylistWritesDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_characteristic_dto(
      ProfileCharacteristicDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_info_dto(
      ProfileInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_query_source_dto(
      QuerySourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_rabbit_air_request_dto(
      RabbitAirRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_64(
      (String, double) self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_16_list_prim_u_8_strict(
      (int, Uint8List) self, SseSerializer serializer);

  @protected
  void sse_encode_scan_match(ScanMatch self, SseSerializer serializer);

  @protected
  void sse_encode_scanned_device_dto(
      ScannedDeviceDto self, SseSerializer serializer);

  @protected
  void sse_encode_security_advisory_dto(
      SecurityAdvisoryDto self, SseSerializer serializer);

  @protected
  void sse_encode_service_dto(ServiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_soap_request_dto(
      SoapRequestDto self, SseSerializer serializer);

  @protected
  void sse_encode_soft_ap_profile_dto(
      SoftApProfileDto self, SseSerializer serializer);

  @protected
  void sse_encode_spec_identity_dto(
      SpecIdentityDto self, SseSerializer serializer);

  @protected
  void sse_encode_stored_play_dto(StoredPlayDto self, SseSerializer serializer);

  @protected
  void sse_encode_stored_upload_dto(
      StoredUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_stored_upload_event_dto(
      StoredUploadEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_stored_upload_event_kind(
      StoredUploadEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_stored_upload_plan_dto(
      StoredUploadPlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wemo_access_point_dto(
      WemoAccessPointDto self, SseSerializer serializer);

  @protected
  void sse_encode_wemo_join_status(
      WemoJoinStatus self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
