// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device_api.dart';
import 'api/mock_api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.9.0';

  @override
  int get rustContentHash => 540483652;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'liberated_bread_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<List<DecodedValueDto>> crateApiDeviceApiDecodeValue(
      {String? specYaml,
      String? serviceUuid,
      required String charUuid,
      required List<int> bytes});

  Future<Uint8List> crateApiDeviceApiEncodeCommand(
      {String? specYaml,
      String? serviceUuid,
      required String charUuid,
      required String commandName,
      required Map<String, double> params});

  Future<ImageWritePlanDto> crateApiDeviceApiEncodeImageFrame(
      {required String specYaml,
      required int width,
      required int height,
      required List<int> rgb,
      required int frameIndex,
      required int maxPayloadPerWrite});

  Future<List<ProfileInfoDto>> crateApiDeviceApiIdentifyStandardProfiles(
      {required List<String> serviceUuids});

  Future<DeviceSpecDto> crateApiDeviceApiLoadDeviceSpec({required String yaml});

  Future<List<MatchResult>> crateApiDeviceApiMatchDeviceToSpec(
      {required List<DeviceSpecDto> specs,
      required String deviceName,
      required List<String> advertisedServiceUuids});

  Future<Uint8List> crateApiMockApiMockReadCharacteristic(
      {required String deviceId,
      required String charUuid,
      required String specYaml});

  Future<void> crateApiMockApiMockReset();

  Future<void> crateApiMockApiMockWriteCharacteristic(
      {required String deviceId,
      required String charUuid,
      required List<int> value});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<DecodedValueDto>> crateApiDeviceApiDecodeValue(
      {String? specYaml,
      String? serviceUuid,
      required String charUuid,
      required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(specYaml, serializer);
        sse_encode_opt_String(serviceUuid, serializer);
        sse_encode_String(charUuid, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_decoded_value_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeviceApiDecodeValueConstMeta,
      argValues: [specYaml, serviceUuid, charUuid, bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiDecodeValueConstMeta =>
      const TaskConstMeta(
        debugName: 'decode_value',
        argNames: ['specYaml', 'serviceUuid', 'charUuid', 'bytes'],
      );

  @override
  Future<Uint8List> crateApiDeviceApiEncodeCommand(
      {String? specYaml,
      String? serviceUuid,
      required String charUuid,
      required String commandName,
      required Map<String, double> params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(specYaml, serializer);
        sse_encode_opt_String(serviceUuid, serializer);
        sse_encode_String(charUuid, serializer);
        sse_encode_String(commandName, serializer);
        sse_encode_Map_String_f_64_None(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeviceApiEncodeCommandConstMeta,
      argValues: [specYaml, serviceUuid, charUuid, commandName, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiEncodeCommandConstMeta =>
      const TaskConstMeta(
        debugName: 'encode_command',
        argNames: [
          'specYaml',
          'serviceUuid',
          'charUuid',
          'commandName',
          'params'
        ],
      );

  @override
  Future<ImageWritePlanDto> crateApiDeviceApiEncodeImageFrame(
      {required String specYaml,
      required int width,
      required int height,
      required List<int> rgb,
      required int frameIndex,
      required int maxPayloadPerWrite}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(specYaml, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        sse_encode_list_prim_u_8_loose(rgb, serializer);
        sse_encode_u_32(frameIndex, serializer);
        sse_encode_u_32(maxPayloadPerWrite, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_image_write_plan_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeviceApiEncodeImageFrameConstMeta,
      argValues: [specYaml, width, height, rgb, frameIndex, maxPayloadPerWrite],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiEncodeImageFrameConstMeta =>
      const TaskConstMeta(
        debugName: 'encode_image_frame',
        argNames: [
          'specYaml',
          'width',
          'height',
          'rgb',
          'frameIndex',
          'maxPayloadPerWrite'
        ],
      );

  @override
  Future<List<ProfileInfoDto>> crateApiDeviceApiIdentifyStandardProfiles(
      {required List<String> serviceUuids}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(serviceUuids, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_profile_info_dto,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeviceApiIdentifyStandardProfilesConstMeta,
      argValues: [serviceUuids],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiIdentifyStandardProfilesConstMeta =>
      const TaskConstMeta(
        debugName: 'identify_standard_profiles',
        argNames: ['serviceUuids'],
      );

  @override
  Future<DeviceSpecDto> crateApiDeviceApiLoadDeviceSpec(
      {required String yaml}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(yaml, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_device_spec_dto,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeviceApiLoadDeviceSpecConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiLoadDeviceSpecConstMeta =>
      const TaskConstMeta(
        debugName: 'load_device_spec',
        argNames: ['yaml'],
      );

  @override
  Future<List<MatchResult>> crateApiDeviceApiMatchDeviceToSpec(
      {required List<DeviceSpecDto> specs,
      required String deviceName,
      required List<String> advertisedServiceUuids}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_device_spec_dto(specs, serializer);
        sse_encode_String(deviceName, serializer);
        sse_encode_list_String(advertisedServiceUuids, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_match_result,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiDeviceApiMatchDeviceToSpecConstMeta,
      argValues: [specs, deviceName, advertisedServiceUuids],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDeviceApiMatchDeviceToSpecConstMeta =>
      const TaskConstMeta(
        debugName: 'match_device_to_spec',
        argNames: ['specs', 'deviceName', 'advertisedServiceUuids'],
      );

  @override
  Future<Uint8List> crateApiMockApiMockReadCharacteristic(
      {required String deviceId,
      required String charUuid,
      required String specYaml}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(charUuid, serializer);
        sse_encode_String(specYaml, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMockApiMockReadCharacteristicConstMeta,
      argValues: [deviceId, charUuid, specYaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMockApiMockReadCharacteristicConstMeta =>
      const TaskConstMeta(
        debugName: 'mock_read_characteristic',
        argNames: ['deviceId', 'charUuid', 'specYaml'],
      );

  @override
  Future<void> crateApiMockApiMockReset() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMockApiMockResetConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMockApiMockResetConstMeta => const TaskConstMeta(
        debugName: 'mock_reset',
        argNames: [],
      );

  @override
  Future<void> crateApiMockApiMockWriteCharacteristic(
      {required String deviceId,
      required String charUuid,
      required List<int> value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(deviceId, serializer);
        sse_encode_String(charUuid, serializer);
        sse_encode_list_prim_u_8_loose(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiMockApiMockWriteCharacteristicConstMeta,
      argValues: [deviceId, charUuid, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMockApiMockWriteCharacteristicConstMeta =>
      const TaskConstMeta(
        debugName: 'mock_write_characteristic',
        argNames: ['deviceId', 'charUuid', 'value'],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Map<String, double> dco_decode_Map_String_f_64_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_f_64(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ImageUploadDto dco_decode_box_autoadd_image_upload_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_upload_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CharacteristicDto dco_decode_characteristic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CharacteristicDto(
      uuid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      canRead: dco_decode_bool(arr[2]),
      canWrite: dco_decode_bool(arr[3]),
      canNotify: dco_decode_bool(arr[4]),
      commands: dco_decode_list_command_dto(arr[5]),
      formatFields: dco_decode_list_format_field_dto(arr[6]),
    );
  }

  @protected
  CommandDto dco_decode_command_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CommandDto(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
      parameters: dco_decode_list_parameter_dto(arr[2]),
      isFixed: dco_decode_bool(arr[3]),
      isEncodable: dco_decode_bool(arr[4]),
      unsupportedEncoding: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  DecodedValueDto dco_decode_decoded_value_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return DecodedValueDto(
      name: dco_decode_String(arr[0]),
      valueType: dco_decode_String(arr[1]),
      display: dco_decode_String(arr[2]),
      boolValue: dco_decode_opt_box_autoadd_bool(arr[3]),
      intValue: dco_decode_opt_box_autoadd_i_64(arr[4]),
      uintValue: dco_decode_opt_box_autoadd_i_64(arr[5]),
      stringValue: dco_decode_opt_String(arr[6]),
      scale: dco_decode_opt_box_autoadd_f_64(arr[7]),
      unit: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  DeviceSpecDto dco_decode_device_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DeviceSpecDto(
      deviceName: dco_decode_String(arr[0]),
      manufacturer: dco_decode_String(arr[1]),
      manufacturerStatus: dco_decode_String(arr[2]),
      protocol: dco_decode_String(arr[3]),
      notes: dco_decode_opt_String(arr[4]),
      localNamePrefix: dco_decode_opt_String(arr[5]),
      serviceUuids: dco_decode_list_String(arr[6]),
      services: dco_decode_list_service_dto(arr[7]),
      entities: dco_decode_list_entity_dto(arr[8]),
      imageUpload: dco_decode_opt_box_autoadd_image_upload_dto(arr[9]),
    );
  }

  @protected
  EntityActionDto dco_decode_entity_action_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return EntityActionDto(
      role: dco_decode_String(arr[0]),
      serviceUuid: dco_decode_String(arr[1]),
      characteristicUuid: dco_decode_String(arr[2]),
      commandName: dco_decode_String(arr[3]),
      userParams: dco_decode_list_String(arr[4]),
      min: dco_decode_opt_box_autoadd_i_64(arr[5]),
      max: dco_decode_opt_box_autoadd_i_64(arr[6]),
    );
  }

  @protected
  EntityDto dco_decode_entity_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return EntityDto(
      name: dco_decode_String(arr[0]),
      platform: dco_decode_opt_String(arr[1]),
      deviceClass: dco_decode_opt_String(arr[2]),
      unit: dco_decode_opt_String(arr[3]),
      stateCharacteristic: dco_decode_opt_String(arr[4]),
      canNotify: dco_decode_bool(arr[5]),
      hasFormat: dco_decode_bool(arr[6]),
      valueField: dco_decode_opt_String(arr[7]),
      valueScale: dco_decode_opt_box_autoadd_f_64(arr[8]),
      onValue: dco_decode_opt_box_autoadd_i_64(arr[9]),
      onWhenNonzero: dco_decode_bool(arr[10]),
      isOnField: dco_decode_opt_String(arr[11]),
      brightnessField: dco_decode_opt_String(arr[12]),
      colorRedField: dco_decode_opt_String(arr[13]),
      colorGreenField: dco_decode_opt_String(arr[14]),
      colorBlueField: dco_decode_opt_String(arr[15]),
      actions: dco_decode_list_entity_action_dto(arr[16]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FormatFieldDto dco_decode_format_field_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FormatFieldDto(
      name: dco_decode_String(arr[0]),
      fieldType: dco_decode_String(arr[1]),
      offset: dco_decode_u_32(arr[2]),
      length: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageUploadDto dco_decode_image_upload_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ImageUploadDto(
      handler: dco_decode_opt_String(arr[0]),
      encodable: dco_decode_bool(arr[1]),
      format: dco_decode_opt_String(arr[2]),
      maxWidth: dco_decode_opt_box_autoadd_u_32(arr[3]),
      maxHeight: dco_decode_opt_box_autoadd_u_32(arr[4]),
      resolutionDeviceReported: dco_decode_bool(arr[5]),
      animation: dco_decode_bool(arr[6]),
      maxFrames: dco_decode_opt_box_autoadd_u_32(arr[7]),
      minFrameIntervalMs: dco_decode_opt_box_autoadd_u_32(arr[8]),
      defaultFrameIntervalMs: dco_decode_opt_box_autoadd_u_32(arr[9]),
    );
  }

  @protected
  ImageWritePlanDto dco_decode_image_write_plan_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImageWritePlanDto(
      serviceUuid: dco_decode_String(arr[0]),
      characteristicUuid: dco_decode_String(arr[1]),
      writes: dco_decode_list_list_prim_u_8_strict(arr[2]),
      nextFrameIndex: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CharacteristicDto> dco_decode_list_characteristic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_characteristic_dto).toList();
  }

  @protected
  List<CommandDto> dco_decode_list_command_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_command_dto).toList();
  }

  @protected
  List<DecodedValueDto> dco_decode_list_decoded_value_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_decoded_value_dto).toList();
  }

  @protected
  List<DeviceSpecDto> dco_decode_list_device_spec_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_device_spec_dto).toList();
  }

  @protected
  List<EntityActionDto> dco_decode_list_entity_action_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entity_action_dto).toList();
  }

  @protected
  List<EntityDto> dco_decode_list_entity_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entity_dto).toList();
  }

  @protected
  List<FormatFieldDto> dco_decode_list_format_field_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_format_field_dto).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_match_result).toList();
  }

  @protected
  List<ParameterDto> dco_decode_list_parameter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_parameter_dto).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProfileCharacteristicDto> dco_decode_list_profile_characteristic_dto(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_profile_characteristic_dto)
        .toList();
  }

  @protected
  List<ProfileInfoDto> dco_decode_list_profile_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile_info_dto).toList();
  }

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_f_64).toList();
  }

  @protected
  List<ServiceDto> dco_decode_list_service_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_service_dto).toList();
  }

  @protected
  MatchResult dco_decode_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MatchResult(
      spec: dco_decode_device_spec_dto(arr[0]),
      matchedByNamePrefix: dco_decode_bool(arr[1]),
      matchedServiceUuids: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ImageUploadDto? dco_decode_opt_box_autoadd_image_upload_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_image_upload_dto(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  Int64List? dco_decode_opt_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_i_64_strict(raw);
  }

  @protected
  ParameterDto dco_decode_parameter_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ParameterDto(
      name: dco_decode_String(arr[0]),
      valueType: dco_decode_String(arr[1]),
      min: dco_decode_opt_box_autoadd_f_64(arr[2]),
      max: dco_decode_opt_box_autoadd_f_64(arr[3]),
      allowed: dco_decode_opt_list_prim_i_64_strict(arr[4]),
      labels: dco_decode_opt_list_String(arr[5]),
    );
  }

  @protected
  ProfileCharacteristicDto dco_decode_profile_characteristic_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProfileCharacteristicDto(
      uuid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      canRead: dco_decode_bool(arr[2]),
      canWrite: dco_decode_bool(arr[3]),
      canNotify: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ProfileInfoDto dco_decode_profile_info_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProfileInfoDto(
      serviceUuid: dco_decode_String(arr[0]),
      profileName: dco_decode_String(arr[1]),
      characteristics: dco_decode_list_profile_characteristic_dto(arr[2]),
    );
  }

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_f_64(arr[1]),
    );
  }

  @protected
  ServiceDto dco_decode_service_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ServiceDto(
      uuid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      characteristics: dco_decode_list_characteristic_dto(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Map<String, double> sse_decode_Map_String_f_64_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_f_64(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ImageUploadDto sse_decode_box_autoadd_image_upload_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_upload_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CharacteristicDto sse_decode_characteristic_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_canRead = sse_decode_bool(deserializer);
    var var_canWrite = sse_decode_bool(deserializer);
    var var_canNotify = sse_decode_bool(deserializer);
    var var_commands = sse_decode_list_command_dto(deserializer);
    var var_formatFields = sse_decode_list_format_field_dto(deserializer);
    return CharacteristicDto(
        uuid: var_uuid,
        name: var_name,
        canRead: var_canRead,
        canWrite: var_canWrite,
        canNotify: var_canNotify,
        commands: var_commands,
        formatFields: var_formatFields);
  }

  @protected
  CommandDto sse_decode_command_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_parameters = sse_decode_list_parameter_dto(deserializer);
    var var_isFixed = sse_decode_bool(deserializer);
    var var_isEncodable = sse_decode_bool(deserializer);
    var var_unsupportedEncoding = sse_decode_opt_String(deserializer);
    return CommandDto(
        name: var_name,
        description: var_description,
        parameters: var_parameters,
        isFixed: var_isFixed,
        isEncodable: var_isEncodable,
        unsupportedEncoding: var_unsupportedEncoding);
  }

  @protected
  DecodedValueDto sse_decode_decoded_value_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_valueType = sse_decode_String(deserializer);
    var var_display = sse_decode_String(deserializer);
    var var_boolValue = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_intValue = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_uintValue = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_stringValue = sse_decode_opt_String(deserializer);
    var var_scale = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_unit = sse_decode_opt_String(deserializer);
    return DecodedValueDto(
        name: var_name,
        valueType: var_valueType,
        display: var_display,
        boolValue: var_boolValue,
        intValue: var_intValue,
        uintValue: var_uintValue,
        stringValue: var_stringValue,
        scale: var_scale,
        unit: var_unit);
  }

  @protected
  DeviceSpecDto sse_decode_device_spec_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceName = sse_decode_String(deserializer);
    var var_manufacturer = sse_decode_String(deserializer);
    var var_manufacturerStatus = sse_decode_String(deserializer);
    var var_protocol = sse_decode_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_localNamePrefix = sse_decode_opt_String(deserializer);
    var var_serviceUuids = sse_decode_list_String(deserializer);
    var var_services = sse_decode_list_service_dto(deserializer);
    var var_entities = sse_decode_list_entity_dto(deserializer);
    var var_imageUpload =
        sse_decode_opt_box_autoadd_image_upload_dto(deserializer);
    return DeviceSpecDto(
        deviceName: var_deviceName,
        manufacturer: var_manufacturer,
        manufacturerStatus: var_manufacturerStatus,
        protocol: var_protocol,
        notes: var_notes,
        localNamePrefix: var_localNamePrefix,
        serviceUuids: var_serviceUuids,
        services: var_services,
        entities: var_entities,
        imageUpload: var_imageUpload);
  }

  @protected
  EntityActionDto sse_decode_entity_action_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_serviceUuid = sse_decode_String(deserializer);
    var var_characteristicUuid = sse_decode_String(deserializer);
    var var_commandName = sse_decode_String(deserializer);
    var var_userParams = sse_decode_list_String(deserializer);
    var var_min = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_max = sse_decode_opt_box_autoadd_i_64(deserializer);
    return EntityActionDto(
        role: var_role,
        serviceUuid: var_serviceUuid,
        characteristicUuid: var_characteristicUuid,
        commandName: var_commandName,
        userParams: var_userParams,
        min: var_min,
        max: var_max);
  }

  @protected
  EntityDto sse_decode_entity_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_platform = sse_decode_opt_String(deserializer);
    var var_deviceClass = sse_decode_opt_String(deserializer);
    var var_unit = sse_decode_opt_String(deserializer);
    var var_stateCharacteristic = sse_decode_opt_String(deserializer);
    var var_canNotify = sse_decode_bool(deserializer);
    var var_hasFormat = sse_decode_bool(deserializer);
    var var_valueField = sse_decode_opt_String(deserializer);
    var var_valueScale = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_onValue = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_onWhenNonzero = sse_decode_bool(deserializer);
    var var_isOnField = sse_decode_opt_String(deserializer);
    var var_brightnessField = sse_decode_opt_String(deserializer);
    var var_colorRedField = sse_decode_opt_String(deserializer);
    var var_colorGreenField = sse_decode_opt_String(deserializer);
    var var_colorBlueField = sse_decode_opt_String(deserializer);
    var var_actions = sse_decode_list_entity_action_dto(deserializer);
    return EntityDto(
        name: var_name,
        platform: var_platform,
        deviceClass: var_deviceClass,
        unit: var_unit,
        stateCharacteristic: var_stateCharacteristic,
        canNotify: var_canNotify,
        hasFormat: var_hasFormat,
        valueField: var_valueField,
        valueScale: var_valueScale,
        onValue: var_onValue,
        onWhenNonzero: var_onWhenNonzero,
        isOnField: var_isOnField,
        brightnessField: var_brightnessField,
        colorRedField: var_colorRedField,
        colorGreenField: var_colorGreenField,
        colorBlueField: var_colorBlueField,
        actions: var_actions);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FormatFieldDto sse_decode_format_field_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_fieldType = sse_decode_String(deserializer);
    var var_offset = sse_decode_u_32(deserializer);
    var var_length = sse_decode_u_32(deserializer);
    return FormatFieldDto(
        name: var_name,
        fieldType: var_fieldType,
        offset: var_offset,
        length: var_length);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageUploadDto sse_decode_image_upload_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handler = sse_decode_opt_String(deserializer);
    var var_encodable = sse_decode_bool(deserializer);
    var var_format = sse_decode_opt_String(deserializer);
    var var_maxWidth = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_maxHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_resolutionDeviceReported = sse_decode_bool(deserializer);
    var var_animation = sse_decode_bool(deserializer);
    var var_maxFrames = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_minFrameIntervalMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_defaultFrameIntervalMs =
        sse_decode_opt_box_autoadd_u_32(deserializer);
    return ImageUploadDto(
        handler: var_handler,
        encodable: var_encodable,
        format: var_format,
        maxWidth: var_maxWidth,
        maxHeight: var_maxHeight,
        resolutionDeviceReported: var_resolutionDeviceReported,
        animation: var_animation,
        maxFrames: var_maxFrames,
        minFrameIntervalMs: var_minFrameIntervalMs,
        defaultFrameIntervalMs: var_defaultFrameIntervalMs);
  }

  @protected
  ImageWritePlanDto sse_decode_image_write_plan_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serviceUuid = sse_decode_String(deserializer);
    var var_characteristicUuid = sse_decode_String(deserializer);
    var var_writes = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_nextFrameIndex = sse_decode_u_32(deserializer);
    return ImageWritePlanDto(
        serviceUuid: var_serviceUuid,
        characteristicUuid: var_characteristicUuid,
        writes: var_writes,
        nextFrameIndex: var_nextFrameIndex);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CharacteristicDto> sse_decode_list_characteristic_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CharacteristicDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_characteristic_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<CommandDto> sse_decode_list_command_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CommandDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_command_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DecodedValueDto> sse_decode_list_decoded_value_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DecodedValueDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_decoded_value_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<DeviceSpecDto> sse_decode_list_device_spec_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DeviceSpecDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_device_spec_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntityActionDto> sse_decode_list_entity_action_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntityActionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entity_action_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntityDto> sse_decode_list_entity_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntityDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entity_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<FormatFieldDto> sse_decode_list_format_field_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FormatFieldDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_format_field_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MatchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_match_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<ParameterDto> sse_decode_list_parameter_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ParameterDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_parameter_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProfileCharacteristicDto> sse_decode_list_profile_characteristic_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileCharacteristicDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_characteristic_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ProfileInfoDto> sse_decode_list_profile_info_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProfileInfoDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile_info_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_f_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<ServiceDto> sse_decode_list_service_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ServiceDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_service_dto(deserializer));
    }
    return ans_;
  }

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spec = sse_decode_device_spec_dto(deserializer);
    var var_matchedByNamePrefix = sse_decode_bool(deserializer);
    var var_matchedServiceUuids = sse_decode_list_String(deserializer);
    return MatchResult(
        spec: var_spec,
        matchedByNamePrefix: var_matchedByNamePrefix,
        matchedServiceUuids: var_matchedServiceUuids);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ImageUploadDto? sse_decode_opt_box_autoadd_image_upload_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_image_upload_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Int64List? sse_decode_opt_list_prim_i_64_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_i_64_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParameterDto sse_decode_parameter_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_valueType = sse_decode_String(deserializer);
    var var_min = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_max = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_allowed = sse_decode_opt_list_prim_i_64_strict(deserializer);
    var var_labels = sse_decode_opt_list_String(deserializer);
    return ParameterDto(
        name: var_name,
        valueType: var_valueType,
        min: var_min,
        max: var_max,
        allowed: var_allowed,
        labels: var_labels);
  }

  @protected
  ProfileCharacteristicDto sse_decode_profile_characteristic_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_canRead = sse_decode_bool(deserializer);
    var var_canWrite = sse_decode_bool(deserializer);
    var var_canNotify = sse_decode_bool(deserializer);
    return ProfileCharacteristicDto(
        uuid: var_uuid,
        name: var_name,
        canRead: var_canRead,
        canWrite: var_canWrite,
        canNotify: var_canNotify);
  }

  @protected
  ProfileInfoDto sse_decode_profile_info_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serviceUuid = sse_decode_String(deserializer);
    var var_profileName = sse_decode_String(deserializer);
    var var_characteristics =
        sse_decode_list_profile_characteristic_dto(deserializer);
    return ProfileInfoDto(
        serviceUuid: var_serviceUuid,
        profileName: var_profileName,
        characteristics: var_characteristics);
  }

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  ServiceDto sse_decode_service_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uuid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_characteristics = sse_decode_list_characteristic_dto(deserializer);
    return ServiceDto(
        uuid: var_uuid, name: var_name, characteristics: var_characteristics);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Map_String_f_64_None(
      Map<String, double> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_f_64(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_upload_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_characteristic_dto(
      CharacteristicDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.canRead, serializer);
    sse_encode_bool(self.canWrite, serializer);
    sse_encode_bool(self.canNotify, serializer);
    sse_encode_list_command_dto(self.commands, serializer);
    sse_encode_list_format_field_dto(self.formatFields, serializer);
  }

  @protected
  void sse_encode_command_dto(CommandDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_list_parameter_dto(self.parameters, serializer);
    sse_encode_bool(self.isFixed, serializer);
    sse_encode_bool(self.isEncodable, serializer);
    sse_encode_opt_String(self.unsupportedEncoding, serializer);
  }

  @protected
  void sse_encode_decoded_value_dto(
      DecodedValueDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.valueType, serializer);
    sse_encode_String(self.display, serializer);
    sse_encode_opt_box_autoadd_bool(self.boolValue, serializer);
    sse_encode_opt_box_autoadd_i_64(self.intValue, serializer);
    sse_encode_opt_box_autoadd_i_64(self.uintValue, serializer);
    sse_encode_opt_String(self.stringValue, serializer);
    sse_encode_opt_box_autoadd_f_64(self.scale, serializer);
    sse_encode_opt_String(self.unit, serializer);
  }

  @protected
  void sse_encode_device_spec_dto(
      DeviceSpecDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.manufacturer, serializer);
    sse_encode_String(self.manufacturerStatus, serializer);
    sse_encode_String(self.protocol, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_opt_String(self.localNamePrefix, serializer);
    sse_encode_list_String(self.serviceUuids, serializer);
    sse_encode_list_service_dto(self.services, serializer);
    sse_encode_list_entity_dto(self.entities, serializer);
    sse_encode_opt_box_autoadd_image_upload_dto(self.imageUpload, serializer);
  }

  @protected
  void sse_encode_entity_action_dto(
      EntityActionDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.serviceUuid, serializer);
    sse_encode_String(self.characteristicUuid, serializer);
    sse_encode_String(self.commandName, serializer);
    sse_encode_list_String(self.userParams, serializer);
    sse_encode_opt_box_autoadd_i_64(self.min, serializer);
    sse_encode_opt_box_autoadd_i_64(self.max, serializer);
  }

  @protected
  void sse_encode_entity_dto(EntityDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.platform, serializer);
    sse_encode_opt_String(self.deviceClass, serializer);
    sse_encode_opt_String(self.unit, serializer);
    sse_encode_opt_String(self.stateCharacteristic, serializer);
    sse_encode_bool(self.canNotify, serializer);
    sse_encode_bool(self.hasFormat, serializer);
    sse_encode_opt_String(self.valueField, serializer);
    sse_encode_opt_box_autoadd_f_64(self.valueScale, serializer);
    sse_encode_opt_box_autoadd_i_64(self.onValue, serializer);
    sse_encode_bool(self.onWhenNonzero, serializer);
    sse_encode_opt_String(self.isOnField, serializer);
    sse_encode_opt_String(self.brightnessField, serializer);
    sse_encode_opt_String(self.colorRedField, serializer);
    sse_encode_opt_String(self.colorGreenField, serializer);
    sse_encode_opt_String(self.colorBlueField, serializer);
    sse_encode_list_entity_action_dto(self.actions, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_format_field_dto(
      FormatFieldDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.fieldType, serializer);
    sse_encode_u_32(self.offset, serializer);
    sse_encode_u_32(self.length, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.handler, serializer);
    sse_encode_bool(self.encodable, serializer);
    sse_encode_opt_String(self.format, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxWidth, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxHeight, serializer);
    sse_encode_bool(self.resolutionDeviceReported, serializer);
    sse_encode_bool(self.animation, serializer);
    sse_encode_opt_box_autoadd_u_32(self.maxFrames, serializer);
    sse_encode_opt_box_autoadd_u_32(self.minFrameIntervalMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.defaultFrameIntervalMs, serializer);
  }

  @protected
  void sse_encode_image_write_plan_dto(
      ImageWritePlanDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serviceUuid, serializer);
    sse_encode_String(self.characteristicUuid, serializer);
    sse_encode_list_list_prim_u_8_strict(self.writes, serializer);
    sse_encode_u_32(self.nextFrameIndex, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_characteristic_dto(
      List<CharacteristicDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_characteristic_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_command_dto(
      List<CommandDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_command_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_decoded_value_dto(
      List<DecodedValueDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_decoded_value_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_device_spec_dto(
      List<DeviceSpecDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_device_spec_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entity_action_dto(
      List<EntityActionDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entity_action_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entity_dto(
      List<EntityDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entity_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_format_field_dto(
      List<FormatFieldDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_format_field_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_match_result(
      List<MatchResult> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_match_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_parameter_dto(
      List<ParameterDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_parameter_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile_characteristic_dto(
      List<ProfileCharacteristicDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_characteristic_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_profile_info_dto(
      List<ProfileInfoDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile_info_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_f_64(
      List<(String, double)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_f_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_service_dto(
      List<ServiceDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_service_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_spec_dto(self.spec, serializer);
    sse_encode_bool(self.matchedByNamePrefix, serializer);
    sse_encode_list_String(self.matchedServiceUuids, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_image_upload_dto(
      ImageUploadDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_image_upload_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_i_64_strict(
      Int64List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_i_64_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_parameter_dto(ParameterDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.valueType, serializer);
    sse_encode_opt_box_autoadd_f_64(self.min, serializer);
    sse_encode_opt_box_autoadd_f_64(self.max, serializer);
    sse_encode_opt_list_prim_i_64_strict(self.allowed, serializer);
    sse_encode_opt_list_String(self.labels, serializer);
  }

  @protected
  void sse_encode_profile_characteristic_dto(
      ProfileCharacteristicDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.canRead, serializer);
    sse_encode_bool(self.canWrite, serializer);
    sse_encode_bool(self.canNotify, serializer);
  }

  @protected
  void sse_encode_profile_info_dto(
      ProfileInfoDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serviceUuid, serializer);
    sse_encode_String(self.profileName, serializer);
    sse_encode_list_profile_characteristic_dto(
        self.characteristics, serializer);
  }

  @protected
  void sse_encode_record_string_f_64(
      (String, double) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
  }

  @protected
  void sse_encode_service_dto(ServiceDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uuid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_characteristic_dto(self.characteristics, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
