// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/device_api.dart';
import 'api/mock_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, double> dco_decode_Map_String_f_64_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ImageUploadDto dco_decode_box_autoadd_image_upload_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CharacteristicDto dco_decode_characteristic_dto(dynamic raw);

  @protected
  CommandDto dco_decode_command_dto(dynamic raw);

  @protected
  DecodedValueDto dco_decode_decoded_value_dto(dynamic raw);

  @protected
  DeviceSpecDto dco_decode_device_spec_dto(dynamic raw);

  @protected
  EntityDto dco_decode_entity_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FormatFieldDto dco_decode_format_field_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageUploadDto dco_decode_image_upload_dto(dynamic raw);

  @protected
  ImageWritePlanDto dco_decode_image_write_plan_dto(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CharacteristicDto> dco_decode_list_characteristic_dto(dynamic raw);

  @protected
  List<CommandDto> dco_decode_list_command_dto(dynamic raw);

  @protected
  List<DecodedValueDto> dco_decode_list_decoded_value_dto(dynamic raw);

  @protected
  List<DeviceSpecDto> dco_decode_list_device_spec_dto(dynamic raw);

  @protected
  List<EntityDto> dco_decode_list_entity_dto(dynamic raw);

  @protected
  List<FormatFieldDto> dco_decode_list_format_field_dto(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MatchResult> dco_decode_list_match_result(dynamic raw);

  @protected
  List<ParameterDto> dco_decode_list_parameter_dto(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProfileCharacteristicDto> dco_decode_list_profile_characteristic_dto(
      dynamic raw);

  @protected
  List<ProfileInfoDto> dco_decode_list_profile_info_dto(dynamic raw);

  @protected
  List<(String, double)> dco_decode_list_record_string_f_64(dynamic raw);

  @protected
  List<ServiceDto> dco_decode_list_service_dto(dynamic raw);

  @protected
  MatchResult dco_decode_match_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ImageUploadDto? dco_decode_opt_box_autoadd_image_upload_dto(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  Int64List? dco_decode_opt_list_prim_i_64_strict(dynamic raw);

  @protected
  ParameterDto dco_decode_parameter_dto(dynamic raw);

  @protected
  ProfileCharacteristicDto dco_decode_profile_characteristic_dto(dynamic raw);

  @protected
  ProfileInfoDto dco_decode_profile_info_dto(dynamic raw);

  @protected
  (String, double) dco_decode_record_string_f_64(dynamic raw);

  @protected
  ServiceDto dco_decode_service_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, double> sse_decode_Map_String_f_64_None(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto sse_decode_box_autoadd_image_upload_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CharacteristicDto sse_decode_characteristic_dto(SseDeserializer deserializer);

  @protected
  CommandDto sse_decode_command_dto(SseDeserializer deserializer);

  @protected
  DecodedValueDto sse_decode_decoded_value_dto(SseDeserializer deserializer);

  @protected
  DeviceSpecDto sse_decode_device_spec_dto(SseDeserializer deserializer);

  @protected
  EntityDto sse_decode_entity_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FormatFieldDto sse_decode_format_field_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto sse_decode_image_upload_dto(SseDeserializer deserializer);

  @protected
  ImageWritePlanDto sse_decode_image_write_plan_dto(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CharacteristicDto> sse_decode_list_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  List<CommandDto> sse_decode_list_command_dto(SseDeserializer deserializer);

  @protected
  List<DecodedValueDto> sse_decode_list_decoded_value_dto(
      SseDeserializer deserializer);

  @protected
  List<DeviceSpecDto> sse_decode_list_device_spec_dto(
      SseDeserializer deserializer);

  @protected
  List<EntityDto> sse_decode_list_entity_dto(SseDeserializer deserializer);

  @protected
  List<FormatFieldDto> sse_decode_list_format_field_dto(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<MatchResult> sse_decode_list_match_result(SseDeserializer deserializer);

  @protected
  List<ParameterDto> sse_decode_list_parameter_dto(
      SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProfileCharacteristicDto> sse_decode_list_profile_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  List<ProfileInfoDto> sse_decode_list_profile_info_dto(
      SseDeserializer deserializer);

  @protected
  List<(String, double)> sse_decode_list_record_string_f_64(
      SseDeserializer deserializer);

  @protected
  List<ServiceDto> sse_decode_list_service_dto(SseDeserializer deserializer);

  @protected
  MatchResult sse_decode_match_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImageUploadDto? sse_decode_opt_box_autoadd_image_upload_dto(
      SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  Int64List? sse_decode_opt_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  ParameterDto sse_decode_parameter_dto(SseDeserializer deserializer);

  @protected
  ProfileCharacteristicDto sse_decode_profile_characteristic_dto(
      SseDeserializer deserializer);

  @protected
  ProfileInfoDto sse_decode_profile_info_dto(SseDeserializer deserializer);

  @protected
  (String, double) sse_decode_record_string_f_64(SseDeserializer deserializer);

  @protected
  ServiceDto sse_decode_service_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_f_64_None(
      Map<String, double> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_characteristic_dto(
      CharacteristicDto self, SseSerializer serializer);

  @protected
  void sse_encode_command_dto(CommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_decoded_value_dto(
      DecodedValueDto self, SseSerializer serializer);

  @protected
  void sse_encode_device_spec_dto(DeviceSpecDto self, SseSerializer serializer);

  @protected
  void sse_encode_entity_dto(EntityDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_format_field_dto(
      FormatFieldDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_upload_dto(
      ImageUploadDto self, SseSerializer serializer);

  @protected
  void sse_encode_image_write_plan_dto(
      ImageWritePlanDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_characteristic_dto(
      List<CharacteristicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_command_dto(
      List<CommandDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_decoded_value_dto(
      List<DecodedValueDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_device_spec_dto(
      List<DeviceSpecDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_dto(
      List<EntityDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_format_field_dto(
      List<FormatFieldDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_match_result(
      List<MatchResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_parameter_dto(
      List<ParameterDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_profile_characteristic_dto(
      List<ProfileCharacteristicDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_profile_info_dto(
      List<ProfileInfoDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_f_64(
      List<(String, double)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_service_dto(
      List<ServiceDto> self, SseSerializer serializer);

  @protected
  void sse_encode_match_result(MatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_upload_dto(
      ImageUploadDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_i_64_strict(
      Int64List? self, SseSerializer serializer);

  @protected
  void sse_encode_parameter_dto(ParameterDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_characteristic_dto(
      ProfileCharacteristicDto self, SseSerializer serializer);

  @protected
  void sse_encode_profile_info_dto(
      ProfileInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_f_64(
      (String, double) self, SseSerializer serializer);

  @protected
  void sse_encode_service_dto(ServiceDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
