// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How much of an address block belongs to this device.
///
/// An OUI names whoever bought the block, which is frequently not who built the
/// product, so the default is deliberately the pessimistic one.
enum MacPrefixConfidence {
  /// The block is shared — subdivided into MA-M/MA-S assignments held by
  /// unrelated companies, or belonging to a third-party radio module's
  /// vendor. Ranks a device, and nothing more.
  low,

  /// The block really is this manufacturer's, but covers their whole
  /// catalogue: "something this vendor made", not "this device".
  medium,

  /// The block is used by this device family and effectively nothing else.
  /// Rare, and it needs evidence.
  high,
  ;
}
