#!/usr/bin/env bash
# Rebuild the LOCAL spec index (index-temp.json) from the vendored specs on
# disk, so a run reflects every spec present — even when the committed
# index.json is stale. Upstream's index.json is regenerated by CI on main; a
# subtree pulled from a local checkout (or a branch CI hasn't indexed) carries
# an index.json that omits specs added since, which is how a spec ends up
# bundled but never loaded (its glyph and controls silently missing).
#
# The app prefers index-temp.json when it is bundled (see device_spec_provider's
# specManifestTempPath). It is gitignored so it never causes the index.json CI
# conflicts. Set LB_SPEC_INDEX=0 to skip. Sourced by run-*.sh and update-specs.

# Rebuild index-temp.json if any vendored spec is newer than it. Expects
# PROJECT_DIR and a `log` function (both provided by the caller). No-op without
# python3.
regen_spec_index() {
  [[ "${LB_SPEC_INDEX:-1}" == "0" ]] && return 0
  local project="${PROJECT_DIR:-$(pwd)}"
  local base="$project/vendor/protocol-specs/device-specs"
  local out="$base/index-temp.json"
  [[ -d "$base/devices" ]] || return 0
  if ! command -v python3 >/dev/null 2>&1; then
    return 0
  fi
  # Rebuild only when a vendored spec is newer than the temp index — cheap, so
  # a launch that changed no spec pays nothing.
  if [[ -f "$out" ]] &&
     [[ -z "$(find "$base/devices" "$base/examples" -name '*.yaml' -newer "$out" -print -quit 2>/dev/null)" ]]; then
    return 0
  fi
  log "Rebuilding the local spec index (index-temp.json) from the vendored specs..."
  python3 - "$base" "$out" << 'PY'
import json, os, sys, glob
base, out = sys.argv[1], sys.argv[2]
entries = []
for sub in ("devices", "examples"):
    for f in sorted(glob.glob(os.path.join(base, sub, "*.yaml"))):
        entries.append({"path": f"device-specs/{sub}/{os.path.basename(f)}"})
with open(out, "w") as fh:
    json.dump(entries, fh)
print(f"  {len(entries)} specs")
PY
}
