// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `char_to_dto`, `command_to_dto`, `decoded_value_to_dto`, `format_field_to_dto`, `manufacturer_status_str`, `parameter_to_dto`, `protocol_str`, `service_to_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Parse a device spec from a YAML string and return a DTO.
Future<DeviceSpecDto> loadDeviceSpec({required String yaml}) =>
    RustLib.instance.api.crateApiDeviceApiLoadDeviceSpec(yaml: yaml);

/// Check if a scanned device matches a spec based on name prefix and/or service UUIDs.
Future<bool> deviceMatchesSpec(
        {required DeviceSpecDto spec,
        required String deviceName,
        required List<String> advertisedServiceUuids}) =>
    RustLib.instance.api.crateApiDeviceApiDeviceMatchesSpec(
        spec: spec,
        deviceName: deviceName,
        advertisedServiceUuids: advertisedServiceUuids);

/// Find the first matching spec for a scanned device.
Future<DeviceSpecDto?> matchDeviceToSpec(
        {required List<DeviceSpecDto> specs,
        required String deviceName,
        required List<String> advertisedServiceUuids}) =>
    RustLib.instance.api.crateApiDeviceApiMatchDeviceToSpec(
        specs: specs,
        deviceName: deviceName,
        advertisedServiceUuids: advertisedServiceUuids);

/// Encode a named command into bytes for a BLE write.
Future<Uint8List> encodeCommand(
        {required String yaml,
        required String charUuid,
        required String commandName,
        required Map<String, double> params}) =>
    RustLib.instance.api.crateApiDeviceApiEncodeCommand(
        yaml: yaml,
        charUuid: charUuid,
        commandName: commandName,
        params: params);

/// Decode raw bytes from a BLE read/notify into named values.
Future<List<DecodedValueDto>> decodeValue(
        {required String yaml,
        required String charUuid,
        required List<int> bytes}) =>
    RustLib.instance.api.crateApiDeviceApiDecodeValue(
        yaml: yaml, charUuid: charUuid, bytes: bytes);

/// Greet — a simple test function to verify the FRB bridge works.
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiDeviceApiGreet(name: name);

/// Given a list of discovered service UUIDs, return info about any that
/// match recognized standard Bluetooth profiles (Battery, Device Info, etc.).
///
/// Services that don't match a standard profile are omitted from the result.
Future<List<ProfileInfoDto>> identifyStandardProfiles(
        {required List<String> serviceUuids}) =>
    RustLib.instance.api
        .crateApiDeviceApiIdentifyStandardProfiles(serviceUuids: serviceUuids);

/// Decode a characteristic value using a built-in standard profile.
///
/// This does not require a YAML device spec — the profile's format is
/// defined by the Bluetooth specification.
Future<List<DecodedValueDto>> decodeStandardProfileValue(
        {required String serviceUuid,
        required String charUuid,
        required List<int> bytes}) =>
    RustLib.instance.api.crateApiDeviceApiDecodeStandardProfileValue(
        serviceUuid: serviceUuid, charUuid: charUuid, bytes: bytes);

class CharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;
  final List<CommandDto> commands;
  final List<FormatFieldDto> formatFields;

  const CharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
    required this.commands,
    required this.formatFields,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode ^
      commands.hashCode ^
      formatFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify &&
          commands == other.commands &&
          formatFields == other.formatFields;
}

class CommandDto {
  final String name;
  final String description;
  final List<ParameterDto> parameters;

  /// true if this is a fixed-value command (no parameters needed).
  final bool isFixed;

  const CommandDto({
    required this.name,
    required this.description,
    required this.parameters,
    required this.isFixed,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      parameters.hashCode ^
      isFixed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          parameters == other.parameters &&
          isFixed == other.isFixed;
}

/// A decoded value from a characteristic read.
class DecodedValueDto {
  final String name;
  final String valueType;
  final String display;
  final bool? boolValue;
  final PlatformInt64? intValue;
  final PlatformInt64? uintValue;
  final String? stringValue;

  const DecodedValueDto({
    required this.name,
    required this.valueType,
    required this.display,
    this.boolValue,
    this.intValue,
    this.uintValue,
    this.stringValue,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      valueType.hashCode ^
      display.hashCode ^
      boolValue.hashCode ^
      intValue.hashCode ^
      uintValue.hashCode ^
      stringValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedValueDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          display == other.display &&
          boolValue == other.boolValue &&
          intValue == other.intValue &&
          uintValue == other.uintValue &&
          stringValue == other.stringValue;
}

/// A parsed device specification, ready for use by the Flutter app.
class DeviceSpecDto {
  final String deviceName;
  final String manufacturer;
  final String manufacturerStatus;
  final String protocol;
  final String? notes;
  final String? localNamePrefix;
  final List<String> serviceUuids;
  final List<ServiceDto> services;

  const DeviceSpecDto({
    required this.deviceName,
    required this.manufacturer,
    required this.manufacturerStatus,
    required this.protocol,
    this.notes,
    this.localNamePrefix,
    required this.serviceUuids,
    required this.services,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      manufacturer.hashCode ^
      manufacturerStatus.hashCode ^
      protocol.hashCode ^
      notes.hashCode ^
      localNamePrefix.hashCode ^
      serviceUuids.hashCode ^
      services.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSpecDto &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          manufacturer == other.manufacturer &&
          manufacturerStatus == other.manufacturerStatus &&
          protocol == other.protocol &&
          notes == other.notes &&
          localNamePrefix == other.localNamePrefix &&
          serviceUuids == other.serviceUuids &&
          services == other.services;
}

class FormatFieldDto {
  final String name;
  final String fieldType;
  final int offset;
  final int length;

  const FormatFieldDto({
    required this.name,
    required this.fieldType,
    required this.offset,
    required this.length,
  });

  @override
  int get hashCode =>
      name.hashCode ^ fieldType.hashCode ^ offset.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatFieldDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fieldType == other.fieldType &&
          offset == other.offset &&
          length == other.length;
}

class ParameterDto {
  final String name;
  final String valueType;
  final double? min;
  final double? max;

  const ParameterDto({
    required this.name,
    required this.valueType,
    this.min,
    this.max,
  });

  @override
  int get hashCode =>
      name.hashCode ^ valueType.hashCode ^ min.hashCode ^ max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParameterDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          min == other.min &&
          max == other.max;
}

/// A characteristic within a standard profile.
class ProfileCharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;

  const ProfileCharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileCharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify;
}

/// Info about a recognized standard Bluetooth profile.
class ProfileInfoDto {
  final String serviceUuid;
  final String profileName;
  final List<ProfileCharacteristicDto> characteristics;

  const ProfileInfoDto({
    required this.serviceUuid,
    required this.profileName,
    required this.characteristics,
  });

  @override
  int get hashCode =>
      serviceUuid.hashCode ^ profileName.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileInfoDto &&
          runtimeType == other.runtimeType &&
          serviceUuid == other.serviceUuid &&
          profileName == other.profileName &&
          characteristics == other.characteristics;
}

class ServiceDto {
  final String uuid;
  final String name;
  final List<CharacteristicDto> characteristics;

  const ServiceDto({
    required this.uuid,
    required this.name,
    required this.characteristics,
  });

  @override
  int get hashCode => uuid.hashCode ^ name.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          characteristics == other.characteristics;
}
