// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `image_upload_dto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Parse a device spec from a YAML string and return a DTO.
Future<DeviceSpecDto> loadDeviceSpec({required String yaml}) =>
    RustLib.instance.api.crateApiDeviceApiLoadDeviceSpec(yaml: yaml);

/// Find every spec matching a scanned device, with the reasons it matched.
///
/// Returns `vec![]` when nothing matches. A spec matches when:
/// - its `local_name_prefix` is a prefix of `device_name`, **or**
/// - any of its `service_uuids` (case-insensitive) appears in `advertised_service_uuids`.
///
/// Both axes are reported separately so the caller can decide how to rank.
Future<List<MatchResult>> matchDeviceToSpec(
        {required List<DeviceSpecDto> specs,
        required String deviceName,
        required List<String> advertisedServiceUuids}) =>
    RustLib.instance.api.crateApiDeviceApiMatchDeviceToSpec(
        specs: specs,
        deviceName: deviceName,
        advertisedServiceUuids: advertisedServiceUuids);

/// Encode a named command into bytes for a BLE write.
///
/// Provide either `spec_yaml` (custom device) or `service_uuid` (standard
/// profile — though standard profiles are read-only). When both are supplied,
/// the spec wins — see [`select_protocol`].
Future<Uint8List> encodeCommand(
        {String? specYaml,
        String? serviceUuid,
        required String charUuid,
        required String commandName,
        required Map<String, double> params}) =>
    RustLib.instance.api.crateApiDeviceApiEncodeCommand(
        specYaml: specYaml,
        serviceUuid: serviceUuid,
        charUuid: charUuid,
        commandName: commandName,
        params: params);

/// Encode one RGB888 frame into the ordered BLE writes that display it,
/// dispatched on the spec's `protocol_handler`.
///
/// `rgb` is row-major, length `width * height * 3`. `frame_index` sequences
/// consecutive frames of an animation (wire serials derive from it), and
/// `max_payload_per_write` is the usable bytes per BLE write (negotiated ATT
/// MTU - 3; pass 20 when the MTU is unknown). Errors are typed and
/// user-presentable: an unknown or missing handler says so instead of
/// producing bytes that were never going to work.
Future<ImageWritePlanDto> encodeImageFrame(
        {required String specYaml,
        required int width,
        required int height,
        required List<int> rgb,
        required int frameIndex,
        required int maxPayloadPerWrite}) =>
    RustLib.instance.api.crateApiDeviceApiEncodeImageFrame(
        specYaml: specYaml,
        width: width,
        height: height,
        rgb: rgb,
        frameIndex: frameIndex,
        maxPayloadPerWrite: maxPayloadPerWrite);

/// Decode raw bytes from a BLE read/notify into named values.
///
/// Provide either `spec_yaml` (custom device) or `service_uuid` (standard
/// profile). When both are supplied, the spec wins — see [`select_protocol`].
Future<List<DecodedValueDto>> decodeValue(
        {String? specYaml,
        String? serviceUuid,
        required String charUuid,
        required List<int> bytes}) =>
    RustLib.instance.api.crateApiDeviceApiDecodeValue(
        specYaml: specYaml,
        serviceUuid: serviceUuid,
        charUuid: charUuid,
        bytes: bytes);

/// Given a list of discovered service UUIDs, return info about any that
/// match recognized standard Bluetooth profiles (Battery, Device Info, etc.).
///
/// Services that don't match a standard profile are omitted from the result.
Future<List<ProfileInfoDto>> identifyStandardProfiles(
        {required List<String> serviceUuids}) =>
    RustLib.instance.api
        .crateApiDeviceApiIdentifyStandardProfiles(serviceUuids: serviceUuids);

class CharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;

  /// Commands in the order the spec declares them. Meaningful — do not sort.
  final List<CommandDto> commands;

  /// Format fields in the order the spec declares them, which is also how the
  /// device packs the value. Meaningful — consumers must not sort this; the
  /// UI lists decoded values in exactly this order.
  final List<FormatFieldDto> formatFields;

  const CharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
    required this.commands,
    required this.formatFields,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode ^
      commands.hashCode ^
      formatFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify &&
          commands == other.commands &&
          formatFields == other.formatFields;
}

class CommandDto {
  final String name;
  final String description;

  /// Parameters in the order the spec declares them. Meaningful — do not sort.
  final List<ParameterDto> parameters;

  /// true if this is a fixed-value command (no parameters needed).
  final bool isFixed;

  /// true when this command can be encoded to bytes.
  final bool isEncodable;

  /// Human-readable encoding name when is_encodable is false.
  final String? unsupportedEncoding;

  const CommandDto({
    required this.name,
    required this.description,
    required this.parameters,
    required this.isFixed,
    required this.isEncodable,
    this.unsupportedEncoding,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      parameters.hashCode ^
      isFixed.hashCode ^
      isEncodable.hashCode ^
      unsupportedEncoding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          parameters == other.parameters &&
          isFixed == other.isFixed &&
          isEncodable == other.isEncodable &&
          unsupportedEncoding == other.unsupportedEncoding;
}

/// A decoded value from a characteristic read.
class DecodedValueDto {
  final String name;
  final String valueType;
  final String display;
  final bool? boolValue;
  final PlatformInt64? intValue;
  final PlatformInt64? uintValue;
  final String? stringValue;

  /// Multiplier from the spec's `format:` block, when it declares one. The
  /// decoded value stays raw so the caller keeps both halves; applying this
  /// is what turns a SIG temperature's 2350 into 23.5.
  final double? scale;

  /// Unit symbol from the spec's `format:` block, used when the entity
  /// surfacing this reading does not name one.
  final String? unit;

  const DecodedValueDto({
    required this.name,
    required this.valueType,
    required this.display,
    this.boolValue,
    this.intValue,
    this.uintValue,
    this.stringValue,
    this.scale,
    this.unit,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      valueType.hashCode ^
      display.hashCode ^
      boolValue.hashCode ^
      intValue.hashCode ^
      uintValue.hashCode ^
      stringValue.hashCode ^
      scale.hashCode ^
      unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedValueDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          display == other.display &&
          boolValue == other.boolValue &&
          intValue == other.intValue &&
          uintValue == other.uintValue &&
          stringValue == other.stringValue &&
          scale == other.scale &&
          unit == other.unit;
}

/// A parsed device specification, ready for use by the Flutter app.
class DeviceSpecDto {
  final String deviceName;
  final String manufacturer;
  final String manufacturerStatus;
  final String protocol;
  final String? notes;
  final String? localNamePrefix;
  final List<String> serviceUuids;
  final List<ServiceDto> services;

  /// Declared sensor/control surfaces that resolve to a real characteristic,
  /// in spec order. This is what lets the app render named readings with
  /// units instead of a raw GATT browser.
  final List<EntityDto> entities;

  /// The spec's `image_upload` feature, when it declares one — pixel
  /// displays (LED matrices, curtain lights, badges, printers) that accept
  /// a raster image and possibly animations. Drives the app's generic LED
  /// image widget; `None` for devices without a pixel surface.
  final ImageUploadDto? imageUpload;

  const DeviceSpecDto({
    required this.deviceName,
    required this.manufacturer,
    required this.manufacturerStatus,
    required this.protocol,
    this.notes,
    this.localNamePrefix,
    required this.serviceUuids,
    required this.services,
    required this.entities,
    this.imageUpload,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      manufacturer.hashCode ^
      manufacturerStatus.hashCode ^
      protocol.hashCode ^
      notes.hashCode ^
      localNamePrefix.hashCode ^
      serviceUuids.hashCode ^
      services.hashCode ^
      entities.hashCode ^
      imageUpload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSpecDto &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          manufacturer == other.manufacturer &&
          manufacturerStatus == other.manufacturerStatus &&
          protocol == other.protocol &&
          notes == other.notes &&
          localNamePrefix == other.localNamePrefix &&
          serviceUuids == other.serviceUuids &&
          services == other.services &&
          entities == other.entities &&
          imageUpload == other.imageUpload;
}

/// A spec-declared reading: what to call it, what unit it is in, and which
/// characteristic carries it.
class EntityDto {
  final String name;

  /// e.g. "sensor". Absent in some hand-written specs.
  final String? platform;

  /// e.g. "temperature", "battery". Drives icon/formatting choices.
  final String? deviceClass;

  /// e.g. "F", "%". Rendered next to the value.
  final String? unit;

  /// UUID of the characteristic carrying this value. Guaranteed to resolve
  /// to a characteristic in this spec — unresolvable entities are dropped.
  final String stateCharacteristic;

  /// Whether the bound characteristic supports notifications, i.e. whether
  /// this reading can stream rather than being polled by read.
  final bool canNotify;

  /// Whether the bound characteristic declares a `format:` block. False means
  /// the value cannot be decoded yet — a spec gap, not an app failure.
  final bool hasFormat;

  /// Name of the decoded field carrying this entity's value, when the spec
  /// declares one. `None` means "use the first decoded field".
  final String? valueField;

  /// Multiplier for the decoded value, e.g. 0.01 when a device reports
  /// centidegrees. `None` means the decoded value is already in `unit`.
  final double? valueScale;

  const EntityDto({
    required this.name,
    this.platform,
    this.deviceClass,
    this.unit,
    required this.stateCharacteristic,
    required this.canNotify,
    required this.hasFormat,
    this.valueField,
    this.valueScale,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      platform.hashCode ^
      deviceClass.hashCode ^
      unit.hashCode ^
      stateCharacteristic.hashCode ^
      canNotify.hashCode ^
      hasFormat.hashCode ^
      valueField.hashCode ^
      valueScale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          platform == other.platform &&
          deviceClass == other.deviceClass &&
          unit == other.unit &&
          stateCharacteristic == other.stateCharacteristic &&
          canNotify == other.canNotify &&
          hasFormat == other.hasFormat &&
          valueField == other.valueField &&
          valueScale == other.valueScale;
}

class FormatFieldDto {
  final String name;
  final String fieldType;
  final int offset;
  final int length;

  const FormatFieldDto({
    required this.name,
    required this.fieldType,
    required this.offset,
    required this.length,
  });

  @override
  int get hashCode =>
      name.hashCode ^ fieldType.hashCode ^ offset.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatFieldDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fieldType == other.fieldType &&
          offset == other.offset &&
          length == other.length;
}

/// A spec's declared image/animation capability, plus whether this crate can
/// actually encode uploads for it.
///
/// The split matters: the capability is *declarative* (any spec may carry
/// it), while encoding needs a named `protocol_handler` implemented in
/// `crate::protocol`. The UI renders the full editor when [`Self::encodable`]
/// and an honest "not wired up yet" state otherwise, so new specs light up by
/// data alone once their handler lands.
class ImageUploadDto {
  /// The spec's `protocol_handler` name, e.g. `daniao_ddp`.
  final String? handler;

  /// True when [`Self::handler`] names a handler this crate implements —
  /// i.e. `encode_image_frame` will succeed rather than error.
  final bool encodable;

  /// Wire pixel format the device expects (e.g. `rgb888`, `gif`).
  final String? format;
  final int? maxWidth;
  final int? maxHeight;

  /// True when max_width/max_height are platform bounds and the panel's
  /// real resolution is reported by the device at runtime (so the editor
  /// should let the user set the canvas size).
  final bool resolutionDeviceReported;

  /// Whether multi-frame sequences (animations) are supported.
  final bool animation;
  final int? maxFrames;

  /// Fastest supported frame flip in milliseconds, when the spec knows it.
  final int? minFrameIntervalMs;
  final int? defaultFrameIntervalMs;

  const ImageUploadDto({
    this.handler,
    required this.encodable,
    this.format,
    this.maxWidth,
    this.maxHeight,
    required this.resolutionDeviceReported,
    required this.animation,
    this.maxFrames,
    this.minFrameIntervalMs,
    this.defaultFrameIntervalMs,
  });

  @override
  int get hashCode =>
      handler.hashCode ^
      encodable.hashCode ^
      format.hashCode ^
      maxWidth.hashCode ^
      maxHeight.hashCode ^
      resolutionDeviceReported.hashCode ^
      animation.hashCode ^
      maxFrames.hashCode ^
      minFrameIntervalMs.hashCode ^
      defaultFrameIntervalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageUploadDto &&
          runtimeType == other.runtimeType &&
          handler == other.handler &&
          encodable == other.encodable &&
          format == other.format &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight &&
          resolutionDeviceReported == other.resolutionDeviceReported &&
          animation == other.animation &&
          maxFrames == other.maxFrames &&
          minFrameIntervalMs == other.minFrameIntervalMs &&
          defaultFrameIntervalMs == other.defaultFrameIntervalMs;
}

/// The BLE writes that push one image frame to a device, in send order.
class ImageWritePlanDto {
  final String serviceUuid;
  final String characteristicUuid;

  /// Ordered write payloads. The caller sends them back-to-back on the
  /// characteristic; ordering is part of the protocol (fragment reassembly).
  final List<Uint8List> writes;

  /// The frame index to pass for the NEXT frame. A frame spanning P wire
  /// packets consumes P sequence numbers, so advancing by 1 would make the
  /// next frame's serials collide with this one's and corrupt fragment
  /// reassembly on the device — always continue from this value.
  final int nextFrameIndex;

  const ImageWritePlanDto({
    required this.serviceUuid,
    required this.characteristicUuid,
    required this.writes,
    required this.nextFrameIndex,
  });

  @override
  int get hashCode =>
      serviceUuid.hashCode ^
      characteristicUuid.hashCode ^
      writes.hashCode ^
      nextFrameIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageWritePlanDto &&
          runtimeType == other.runtimeType &&
          serviceUuid == other.serviceUuid &&
          characteristicUuid == other.characteristicUuid &&
          writes == other.writes &&
          nextFrameIndex == other.nextFrameIndex;
}

/// One match returned by [`match_device_to_spec`]. Callers pick whichever
/// match suits them — sort by `matched_service_uuids.len()`, prefer name-prefix
/// matches, etc.
class MatchResult {
  final DeviceSpecDto spec;
  final bool matchedByNamePrefix;

  /// The advertised service UUIDs (lowercased) that intersect with the
  /// spec's identification. Empty when no UUIDs matched.
  final List<String> matchedServiceUuids;

  const MatchResult({
    required this.spec,
    required this.matchedByNamePrefix,
    required this.matchedServiceUuids,
  });

  @override
  int get hashCode =>
      spec.hashCode ^
      matchedByNamePrefix.hashCode ^
      matchedServiceUuids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchResult &&
          runtimeType == other.runtimeType &&
          spec == other.spec &&
          matchedByNamePrefix == other.matchedByNamePrefix &&
          matchedServiceUuids == other.matchedServiceUuids;
}

class ParameterDto {
  final String name;
  final String valueType;
  final double? min;
  final double? max;

  /// Enumerated set of allowed values. When present (and non-empty) the
  /// device accepts only these values, so the UI should offer a choice
  /// among them instead of a free min..max range.
  final Int64List? allowed;

  /// Human-readable labels for `allowed`, paired 1:1 by index (the upstream
  /// spec-format contract). Only present when `allowed` is present and the
  /// lengths match exactly — a mismatched spec keeps its `allowed` values
  /// but has its labels dropped rather than mispaired (see the `From`
  /// conversion below).
  final List<String>? labels;

  const ParameterDto({
    required this.name,
    required this.valueType,
    this.min,
    this.max,
    this.allowed,
    this.labels,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      valueType.hashCode ^
      min.hashCode ^
      max.hashCode ^
      allowed.hashCode ^
      labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParameterDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          min == other.min &&
          max == other.max &&
          allowed == other.allowed &&
          labels == other.labels;
}

/// A characteristic within a standard profile.
class ProfileCharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;

  const ProfileCharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileCharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify;
}

/// Info about a recognized standard Bluetooth profile.
class ProfileInfoDto {
  final String serviceUuid;
  final String profileName;
  final List<ProfileCharacteristicDto> characteristics;

  const ProfileInfoDto({
    required this.serviceUuid,
    required this.profileName,
    required this.characteristics,
  });

  @override
  int get hashCode =>
      serviceUuid.hashCode ^ profileName.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileInfoDto &&
          runtimeType == other.runtimeType &&
          serviceUuid == other.serviceUuid &&
          profileName == other.profileName &&
          characteristics == other.characteristics;
}

class ServiceDto {
  final String uuid;
  final String name;
  final List<CharacteristicDto> characteristics;

  const ServiceDto({
    required this.uuid,
    required this.name,
    required this.characteristics,
  });

  @override
  int get hashCode => uuid.hashCode ^ name.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          characteristics == other.characteristics;
}
