// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Parse a device spec from a YAML string and return a DTO.
Future<DeviceSpecDto> loadDeviceSpec({required String yaml}) =>
    RustLib.instance.api.crateApiDeviceApiLoadDeviceSpec(yaml: yaml);

/// Find every spec matching a scanned device, with the reasons it matched.
///
/// Returns `vec![]` when nothing matches. A spec matches when:
/// - its `local_name_prefix` is a prefix of `device_name`, **or**
/// - any of its `service_uuids` (case-insensitive) appears in `advertised_service_uuids`.
///
/// Both axes are reported separately so the caller can decide how to rank.
Future<List<MatchResult>> matchDeviceToSpec(
        {required List<DeviceSpecDto> specs,
        required String deviceName,
        required List<String> advertisedServiceUuids}) =>
    RustLib.instance.api.crateApiDeviceApiMatchDeviceToSpec(
        specs: specs,
        deviceName: deviceName,
        advertisedServiceUuids: advertisedServiceUuids);

/// Encode a named command into bytes for a BLE write.
///
/// Provide either `spec_yaml` (custom device) or `service_uuid` (standard
/// profile — though standard profiles are read-only). When both are supplied,
/// the spec wins — see [`select_protocol`].
Future<Uint8List> encodeCommand(
        {String? specYaml,
        String? serviceUuid,
        required String charUuid,
        required String commandName,
        required Map<String, double> params}) =>
    RustLib.instance.api.crateApiDeviceApiEncodeCommand(
        specYaml: specYaml,
        serviceUuid: serviceUuid,
        charUuid: charUuid,
        commandName: commandName,
        params: params);

/// Decode raw bytes from a BLE read/notify into named values.
///
/// Provide either `spec_yaml` (custom device) or `service_uuid` (standard
/// profile). When both are supplied, the spec wins — see [`select_protocol`].
Future<List<DecodedValueDto>> decodeValue(
        {String? specYaml,
        String? serviceUuid,
        required String charUuid,
        required List<int> bytes}) =>
    RustLib.instance.api.crateApiDeviceApiDecodeValue(
        specYaml: specYaml,
        serviceUuid: serviceUuid,
        charUuid: charUuid,
        bytes: bytes);

/// Given a list of discovered service UUIDs, return info about any that
/// match recognized standard Bluetooth profiles (Battery, Device Info, etc.).
///
/// Services that don't match a standard profile are omitted from the result.
Future<List<ProfileInfoDto>> identifyStandardProfiles(
        {required List<String> serviceUuids}) =>
    RustLib.instance.api
        .crateApiDeviceApiIdentifyStandardProfiles(serviceUuids: serviceUuids);

class CharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;

  /// Commands in the order the spec declares them. Meaningful — do not sort.
  final List<CommandDto> commands;

  /// Format fields in the order the spec declares them, which is also how the
  /// device packs the value. Meaningful — consumers must not sort this; the
  /// UI lists decoded values in exactly this order.
  final List<FormatFieldDto> formatFields;

  const CharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
    required this.commands,
    required this.formatFields,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode ^
      commands.hashCode ^
      formatFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify &&
          commands == other.commands &&
          formatFields == other.formatFields;
}

class CommandDto {
  final String name;
  final String description;

  /// Parameters in the order the spec declares them. Meaningful — do not sort.
  final List<ParameterDto> parameters;

  /// true if this is a fixed-value command (no parameters needed).
  final bool isFixed;

  /// true when this command can be encoded to bytes.
  final bool isEncodable;

  /// Human-readable encoding name when is_encodable is false.
  final String? unsupportedEncoding;

  const CommandDto({
    required this.name,
    required this.description,
    required this.parameters,
    required this.isFixed,
    required this.isEncodable,
    this.unsupportedEncoding,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      parameters.hashCode ^
      isFixed.hashCode ^
      isEncodable.hashCode ^
      unsupportedEncoding.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          parameters == other.parameters &&
          isFixed == other.isFixed &&
          isEncodable == other.isEncodable &&
          unsupportedEncoding == other.unsupportedEncoding;
}

/// A decoded value from a characteristic read.
class DecodedValueDto {
  final String name;
  final String valueType;
  final String display;
  final bool? boolValue;
  final PlatformInt64? intValue;
  final PlatformInt64? uintValue;
  final String? stringValue;

  const DecodedValueDto({
    required this.name,
    required this.valueType,
    required this.display,
    this.boolValue,
    this.intValue,
    this.uintValue,
    this.stringValue,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      valueType.hashCode ^
      display.hashCode ^
      boolValue.hashCode ^
      intValue.hashCode ^
      uintValue.hashCode ^
      stringValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedValueDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          display == other.display &&
          boolValue == other.boolValue &&
          intValue == other.intValue &&
          uintValue == other.uintValue &&
          stringValue == other.stringValue;
}

/// A parsed device specification, ready for use by the Flutter app.
class DeviceSpecDto {
  final String deviceName;
  final String manufacturer;
  final String manufacturerStatus;
  final String protocol;
  final String? notes;
  final String? localNamePrefix;
  final List<String> serviceUuids;
  final List<ServiceDto> services;

  const DeviceSpecDto({
    required this.deviceName,
    required this.manufacturer,
    required this.manufacturerStatus,
    required this.protocol,
    this.notes,
    this.localNamePrefix,
    required this.serviceUuids,
    required this.services,
  });

  @override
  int get hashCode =>
      deviceName.hashCode ^
      manufacturer.hashCode ^
      manufacturerStatus.hashCode ^
      protocol.hashCode ^
      notes.hashCode ^
      localNamePrefix.hashCode ^
      serviceUuids.hashCode ^
      services.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceSpecDto &&
          runtimeType == other.runtimeType &&
          deviceName == other.deviceName &&
          manufacturer == other.manufacturer &&
          manufacturerStatus == other.manufacturerStatus &&
          protocol == other.protocol &&
          notes == other.notes &&
          localNamePrefix == other.localNamePrefix &&
          serviceUuids == other.serviceUuids &&
          services == other.services;
}

class FormatFieldDto {
  final String name;
  final String fieldType;
  final int offset;
  final int length;

  const FormatFieldDto({
    required this.name,
    required this.fieldType,
    required this.offset,
    required this.length,
  });

  @override
  int get hashCode =>
      name.hashCode ^ fieldType.hashCode ^ offset.hashCode ^ length.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FormatFieldDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fieldType == other.fieldType &&
          offset == other.offset &&
          length == other.length;
}

/// One match returned by [`match_device_to_spec`]. Callers pick whichever
/// match suits them — sort by `matched_service_uuids.len()`, prefer name-prefix
/// matches, etc.
class MatchResult {
  final DeviceSpecDto spec;
  final bool matchedByNamePrefix;

  /// The advertised service UUIDs (lowercased) that intersect with the
  /// spec's identification. Empty when no UUIDs matched.
  final List<String> matchedServiceUuids;

  const MatchResult({
    required this.spec,
    required this.matchedByNamePrefix,
    required this.matchedServiceUuids,
  });

  @override
  int get hashCode =>
      spec.hashCode ^
      matchedByNamePrefix.hashCode ^
      matchedServiceUuids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MatchResult &&
          runtimeType == other.runtimeType &&
          spec == other.spec &&
          matchedByNamePrefix == other.matchedByNamePrefix &&
          matchedServiceUuids == other.matchedServiceUuids;
}

class ParameterDto {
  final String name;
  final String valueType;
  final double? min;
  final double? max;

  const ParameterDto({
    required this.name,
    required this.valueType,
    this.min,
    this.max,
  });

  @override
  int get hashCode =>
      name.hashCode ^ valueType.hashCode ^ min.hashCode ^ max.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParameterDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          valueType == other.valueType &&
          min == other.min &&
          max == other.max;
}

/// A characteristic within a standard profile.
class ProfileCharacteristicDto {
  final String uuid;
  final String name;
  final bool canRead;
  final bool canWrite;
  final bool canNotify;

  const ProfileCharacteristicDto({
    required this.uuid,
    required this.name,
    required this.canRead,
    required this.canWrite,
    required this.canNotify,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      name.hashCode ^
      canRead.hashCode ^
      canWrite.hashCode ^
      canNotify.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileCharacteristicDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          canRead == other.canRead &&
          canWrite == other.canWrite &&
          canNotify == other.canNotify;
}

/// Info about a recognized standard Bluetooth profile.
class ProfileInfoDto {
  final String serviceUuid;
  final String profileName;
  final List<ProfileCharacteristicDto> characteristics;

  const ProfileInfoDto({
    required this.serviceUuid,
    required this.profileName,
    required this.characteristics,
  });

  @override
  int get hashCode =>
      serviceUuid.hashCode ^ profileName.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileInfoDto &&
          runtimeType == other.runtimeType &&
          serviceUuid == other.serviceUuid &&
          profileName == other.profileName &&
          characteristics == other.characteristics;
}

class ServiceDto {
  final String uuid;
  final String name;
  final List<CharacteristicDto> characteristics;

  const ServiceDto({
    required this.uuid,
    required this.name,
    required this.characteristics,
  });

  @override
  int get hashCode => uuid.hashCode ^ name.hashCode ^ characteristics.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceDto &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          name == other.name &&
          characteristics == other.characteristics;
}
