// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `warn_spec_failure_once`

/// Reset all mock device state. Call when starting a new mock session.
Future<void> mockReset() => RustLib.instance.api.crateApiMockApiMockReset();

/// Simulate reading a characteristic value for a mock device.
///
/// Uses the device spec to determine the format and generate appropriate
/// bytes. Spec parse failures are logged once per `(char_uuid, message)`
/// pair to stderr — repeated reads against a broken YAML won't spam — and
/// the read falls back to a fixed-length zero buffer.
Future<Uint8List> mockReadCharacteristic(
        {required String deviceId,
        required String charUuid,
        required String specYaml}) =>
    RustLib.instance.api.crateApiMockApiMockReadCharacteristic(
        deviceId: deviceId, charUuid: charUuid, specYaml: specYaml);

/// Simulate writing a characteristic value for a mock device.
Future<void> mockWriteCharacteristic(
        {required String deviceId,
        required String charUuid,
        required List<int> value}) =>
    RustLib.instance.api.crateApiMockApiMockWriteCharacteristic(
        deviceId: deviceId, charUuid: charUuid, value: value);
