// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'device_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `brother_placement`, `raster_print_dto`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BrotherPlacement`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

/// The spec's raster-print surface, or None when the spec is not a raster
/// printer (no `raster_print` marker, or no `image_upload` entry beside it).
Future<RasterPrintDto?> rasterPrintForSpec({required String specYaml}) =>
    RustLib.instance.api.crateApiPrintApiRasterPrintForSpec(specYaml: specYaml);

/// Reduce a composed RGBA canvas (straight alpha) to the black-and-white
/// RGB888 every raster printer encoder takes, and the preview shows.
Future<Uint8List> preparePrintRaster({
  required List<int> rgba,
  required int width,
  required int height,
  required PrintDither dither,
  required int threshold,
}) => RustLib.instance.api.crateApiPrintApiPreparePrintRaster(
  rgba: rgba,
  width: width,
  height: height,
  dither: dither,
  threshold: threshold,
);

/// The canvas to compose a Brother QL label on, for the media the printer
/// reported (or the caller assumed).
Future<LabelCanvasDto> brotherQlLabelCanvas({
  required String specYaml,
  required BrotherQlJobParamsDto params,
}) => RustLib.instance.api.crateApiPrintApiBrotherQlLabelCanvas(
  specYaml: specYaml,
  params: params,
);

/// Encode a composed label as a Brother QL raster job. `rgb` is RGB888 of
/// `width` x `height`, at most the canvas [`brother_ql_label_canvas`] gives;
/// a narrower canvas is centred in the printable width. The result is the
/// whole byte stream for TCP 9100.
Future<Uint8List> renderBrotherQlJob({
  required String specYaml,
  required BrotherQlJobParamsDto params,
  required List<int> rgb,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiPrintApiRenderBrotherQlJob(
  specYaml: specYaml,
  params: params,
  rgb: rgb,
  width: width,
  height: height,
);

/// The canvas a Brother QL label should be composed on for the loaded roll.
class LabelCanvasDto {
  /// Dots across the tape that print.
  final int widthDots;

  /// Dots along the feed that print, for a die-cut label; None for
  /// continuous tape, whose length the content decides.
  final int? lengthDots;
  final int dpi;

  /// The spec's name for the roll ("62mm continuous (DK-22205)"), when the
  /// loaded media matched one.
  final String? mediaName;

  const LabelCanvasDto({
    required this.widthDots,
    this.lengthDots,
    required this.dpi,
    this.mediaName,
  });

  @override
  int get hashCode =>
      widthDots.hashCode ^
      lengthDots.hashCode ^
      dpi.hashCode ^
      mediaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LabelCanvasDto &&
          runtimeType == other.runtimeType &&
          widthDots == other.widthDots &&
          lengthDots == other.lengthDots &&
          dpi == other.dpi &&
          mediaName == other.mediaName;
}

/// A closed choice (density, paper type): wire values with labels.
class PrintChoiceDto {
  final Int64List allowed;
  final List<String> labels;
  final PlatformInt64? defaultValue;
  final String? command;

  const PrintChoiceDto({
    required this.allowed,
    required this.labels,
    this.defaultValue,
    this.command,
  });

  @override
  int get hashCode =>
      allowed.hashCode ^
      labels.hashCode ^
      defaultValue.hashCode ^
      command.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrintChoiceDto &&
          runtimeType == other.runtimeType &&
          allowed == other.allowed &&
          labels == other.labels &&
          defaultValue == other.defaultValue &&
          command == other.command;
}

/// How [`prepare_print_raster`] turns grey into black and white.
enum PrintDither {
  /// A hard cut at the threshold — text, QR codes, line art.
  threshold,

  /// Floyd–Steinberg error diffusion — photos.
  floydSteinberg,

  /// Atkinson error diffusion — photos, lighter and crisper.
  atkinson,
}

/// One loadable roll or tape.
class PrintMediaDto {
  final String name;

  /// `continuous`, `die_cut` or `round_die_cut`.
  final String kind;
  final double widthMm;
  final double? lengthMm;

  /// Dots of this roll that print, across the head.
  final int? printWidthDots;

  /// Dots of one label that print, along the feed (die-cut only).
  final int? printLengthDots;

  const PrintMediaDto({
    required this.name,
    required this.kind,
    required this.widthMm,
    this.lengthMm,
    this.printWidthDots,
    this.printLengthDots,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      kind.hashCode ^
      widthMm.hashCode ^
      lengthMm.hashCode ^
      printWidthDots.hashCode ^
      printLengthDots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrintMediaDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind &&
          widthMm == other.widthMm &&
          lengthMm == other.lengthMm &&
          printWidthDots == other.printWidthDots &&
          printLengthDots == other.printLengthDots;
}

/// A raster printer's print surface, resolved from its spec.
class RasterPrintDto {
  /// The spec's `protocol_handler`, when it names one.
  final String? handler;

  /// `raw_stream` (write the job to a TCP socket) or `ble_write_plan` (run
  /// the image-upload write plan over GATT). None when this build has no
  /// encoder for the handler — the printer is known but not printable.
  final String? transport;

  /// True when [`Self::transport`] is set: a print from this app will work.
  final bool encodable;

  /// Head resolution. Falls back to 203 when the spec states none, and
  /// [`Self::dpi_assumed`] says so.
  final int dpi;
  final bool dpiAssumed;

  /// Dots across the head.
  final int? headDots;

  /// Widest canvas that actually prints: `printable_dots`, else
  /// `head_dots`, else the image feature's `max_width`.
  final int? printableDots;

  /// Longest label the printer produces, in feed dots.
  final int? maxLengthDots;

  /// Loadable rolls and tapes, in spec order. Empty when the spec lists
  /// none (the BLE thermal printers take whatever roll fits the head).
  final List<PrintMediaDto> media;
  final PrintChoiceDto? density;
  final PrintChoiceDto? paperType;

  /// The spec variants this print surface belongs to; empty for every
  /// model. A caller that knows which variant it is connected to offers
  /// printing only when that one is listed.
  final List<String> variants;

  /// True unless the spec says it has not been run against real hardware
  /// (`device.testing.status: untested`) — the composer says so, rather
  /// than let a first print on a reported-only protocol look routine.
  final bool hardwareTested;

  const RasterPrintDto({
    this.handler,
    this.transport,
    required this.encodable,
    required this.dpi,
    required this.dpiAssumed,
    this.headDots,
    this.printableDots,
    this.maxLengthDots,
    required this.media,
    this.density,
    this.paperType,
    required this.variants,
    required this.hardwareTested,
  });

  @override
  int get hashCode =>
      handler.hashCode ^
      transport.hashCode ^
      encodable.hashCode ^
      dpi.hashCode ^
      dpiAssumed.hashCode ^
      headDots.hashCode ^
      printableDots.hashCode ^
      maxLengthDots.hashCode ^
      media.hashCode ^
      density.hashCode ^
      paperType.hashCode ^
      variants.hashCode ^
      hardwareTested.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RasterPrintDto &&
          runtimeType == other.runtimeType &&
          handler == other.handler &&
          transport == other.transport &&
          encodable == other.encodable &&
          dpi == other.dpi &&
          dpiAssumed == other.dpiAssumed &&
          headDots == other.headDots &&
          printableDots == other.printableDots &&
          maxLengthDots == other.maxLengthDots &&
          media == other.media &&
          density == other.density &&
          paperType == other.paperType &&
          variants == other.variants &&
          hardwareTested == other.hardwareTested;
}
