// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `block_dtos`, `from_channel`, `from_limit`, `from_tone`, `model_or_error`, `none`, `to_channel`, `to_limit`, `to_tone`, `uv5r_model_or_error`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Every radio this codec can program.
Future<List<RadioModelDto>> radioModels() =>
    RustLib.instance.api.crateApiRadioApiRadioModels();

/// The string that puts this radio into programming mode.
Future<Uint8List> radioIdentMagic({required String modelId}) =>
    RustLib.instance.api.crateApiRadioApiRadioIdentMagic(modelId: modelId);

/// The byte the radio answers a good command with.
Future<int> radioAckByte() =>
    RustLib.instance.api.crateApiRadioApiRadioAckByte();

/// The handshake to run once the ident magic has been acknowledged.
Future<List<HandshakeStepDto>> radioHandshakeSteps() =>
    RustLib.instance.api.crateApiRadioApiRadioHandshakeSteps();

/// Every block of a full read, in order.
Future<List<CodeplugBlockDto>> radioReadPlan({required String modelId}) =>
    RustLib.instance.api.crateApiRadioApiRadioReadPlan(modelId: modelId);

/// Every block of a full write, in order.
///
/// `block_size` is a parameter because the radio's own Bluetooth takes
/// 0x80-byte writes while a cable takes 0x40 -- one codec, two callers.
Future<List<CodeplugBlockDto>> radioWritePlan({
  required String modelId,
  required int blockSize,
}) => RustLib.instance.api.crateApiRadioApiRadioWritePlan(
  modelId: modelId,
  blockSize: blockSize,
);

/// The write block size the radio's own Bluetooth expects.
Future<int> radioBleWriteBlockSize() =>
    RustLib.instance.api.crateApiRadioApiRadioBleWriteBlockSize();

/// The request that reads `len` bytes from `addr`.
Future<Uint8List> radioReadCommand({required int addr, required int len}) =>
    RustLib.instance.api.crateApiRadioApiRadioReadCommand(addr: addr, len: len);

/// How many bytes that read will answer with, header included.
///
/// Over Bluetooth the reply arrives in ~20-byte notifications; this is how
/// the Dart side tells "still arriving" from "done".
Future<int> radioExpectedReplyLen({required int len}) =>
    RustLib.instance.api.crateApiRadioApiRadioExpectedReplyLen(len: len);

/// The payload of a read reply, substitution undone and header checked.
Future<Uint8List> radioParseReadReply({
  required List<int> reply,
  required int addr,
  required int len,
}) => RustLib.instance.api.crateApiRadioApiRadioParseReadReply(
  reply: reply,
  addr: addr,
  len: len,
);

/// The request that writes `data` to `addr`.
Future<Uint8List> radioWriteCommand({
  required int addr,
  required List<int> data,
}) => RustLib.instance.api.crateApiRadioApiRadioWriteCommand(
  addr: addr,
  data: data,
);

/// Whether a reply is the radio's acknowledgement.
Future<bool> radioIsAck({required List<int> reply}) =>
    RustLib.instance.api.crateApiRadioApiRadioIsAck(reply: reply);

/// The channels in a codeplug image. Empty slots are omitted; each channel
/// carries the slot it came from.
Future<List<RadioChannelDto>> radioDecodeChannels({
  required List<int> image,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioDecodeChannels(
  image: image,
  modelId: modelId,
);

/// A copy of `image` with `channels` written from slot 1 up and the rest of
/// the slots cleared.
///
/// Everything outside the channel records survives: the settings, the DTMF
/// codes, the parts of each record this codec does not model.
Future<Uint8List> radioEncodeChannels({
  required List<int> image,
  required List<RadioChannelDto> channels,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioEncodeChannels(
  image: image,
  channels: channels,
  modelId: modelId,
);

/// Whether an image is the size this model reads back.
///
/// Checked before a write, because an image of the wrong length means the
/// read that produced it was cut short, and writing it back would leave the
/// radio holding half a codeplug.
Future<bool> radioImageIsComplete({
  required int imageLen,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioImageIsComplete(
  imageLen: imageLen,
  modelId: modelId,
);

/// Every radio of the family this codec programs.
Future<List<Uv5rModelDto>> uv5RModels() =>
    RustLib.instance.api.crateApiRadioApiUv5RModels();

/// The ident magics to try for this radio, in order.
Future<List<Uint8List>> uv5RIdentMagics({required String modelId}) =>
    RustLib.instance.api.crateApiRadioApiUv5RIdentMagics(modelId: modelId);

Future<int> uv5RBaudRate() =>
    RustLib.instance.api.crateApiRadioApiUv5RBaudRate();

/// The byte that asks an acknowledged radio for its ident.
Future<int> uv5RIdentRequest() =>
    RustLib.instance.api.crateApiRadioApiUv5RIdentRequest();

/// Whether the ident read so far is all of it.
Future<bool> uv5RIdentReplyComplete({required List<int> reply}) =>
    RustLib.instance.api.crateApiRadioApiUv5RIdentReplyComplete(reply: reply);

/// The eight-byte ident, from however the radio sent it.
Future<Uint8List> uv5RParseIdent({required List<int> reply}) =>
    RustLib.instance.api.crateApiRadioApiUv5RParseIdent(reply: reply);

/// The reads made right after the ident, before the image is read.
///
/// The first is the session's first command, answered without a leading
/// acknowledgement; every later answer has one.
Future<List<ReadRequestDto>> uv5RProbeReads() =>
    RustLib.instance.api.crateApiRadioApiUv5RProbeReads();

/// What the second and third probe reads say.
Future<Uv5rProbeDto> uv5RParseProbe({
  required List<int> firmwareBlock,
  required List<int> dropBlock,
}) => RustLib.instance.api.crateApiRadioApiUv5RParseProbe(
  firmwareBlock: firmwareBlock,
  dropBlock: dropBlock,
);

/// Every read of the image after the probe, in image order. The session's
/// eight ident bytes come first in the image; these fill the rest.
Future<List<CodeplugBlockDto>> uv5RReadPlan({required bool dropsByte}) =>
    RustLib.instance.api.crateApiRadioApiUv5RReadPlan(dropsByte: dropsByte);

Future<int> uv5RImageLen() =>
    RustLib.instance.api.crateApiRadioApiUv5RImageLen();

Future<Uint8List> uv5RReadCommand({required int addr, required int len}) =>
    RustLib.instance.api.crateApiRadioApiUv5RReadCommand(addr: addr, len: len);

/// How many bytes a read's answer is, not counting its leading ack.
Future<int> uv5RReadReplyLen({required int len}) =>
    RustLib.instance.api.crateApiRadioApiUv5RReadReplyLen(len: len);

Future<Uint8List> uv5RParseReadReply({
  required List<int> reply,
  required int addr,
  required int len,
}) => RustLib.instance.api.crateApiRadioApiUv5RParseReadReply(
  reply: reply,
  addr: addr,
  len: len,
);

Future<Uint8List> uv5RWriteCommand({
  required int addr,
  required List<int> data,
}) => RustLib.instance.api.crateApiRadioApiUv5RWriteCommand(
  addr: addr,
  data: data,
);

/// The firmware string an image carries.
Future<String> uv5RFirmware({required List<int> image}) =>
    RustLib.instance.api.crateApiRadioApiUv5RFirmware(image: image);

/// The channels in an image. Empty slots are omitted; each channel carries
/// the slot it came from.
Future<List<RadioChannelDto>> uv5RDecodeChannels({
  required List<int> image,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5RDecodeChannels(
  image: image,
  modelId: modelId,
);

/// A copy of `image` with `channels` from slot 1 up and every later slot
/// cleared, keeping what the app does not model.
Future<Uint8List> uv5REncodeChannels({
  required List<int> image,
  required List<RadioChannelDto> channels,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5REncodeChannels(
  image: image,
  channels: channels,
  modelId: modelId,
);

/// The blocks to write to turn the radio from `base` into `updated`: only
/// those that differ, and an error if any of them is somewhere this app never
/// writes.
Future<List<CodeplugBlockDto>> uv5RChangedBlocks({
  required List<int> base,
  required List<int> updated,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5RChangedBlocks(
  base: base,
  updated: updated,
  modelId: modelId,
);

/// Every block a full restore of `image` writes.
Future<List<CodeplugBlockDto>> uv5RRestorePlan({
  required List<int> image,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5RRestorePlan(
  image: image,
  modelId: modelId,
);

/// The transmit limits an image holds, read from whichever layout the
/// radio's firmware uses.
Future<BandLimitsDto> uv5RReadBandLimits({
  required List<int> image,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5RReadBandLimits(
  image: image,
  modelId: modelId,
);

/// A copy of `image` with `limits` written, and nothing else changed.
Future<Uint8List> uv5RApplyBandLimits({
  required List<int> image,
  required BandLimitsDto limits,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiUv5RApplyBandLimits(
  image: image,
  limits: limits,
  modelId: modelId,
);

/// One band's transmit limits, in whole megahertz.
class BandLimitDto {
  final bool txEnabled;
  final int lowerMhz;
  final int upperMhz;

  const BandLimitDto({
    required this.txEnabled,
    required this.lowerMhz,
    required this.upperMhz,
  });

  @override
  int get hashCode =>
      txEnabled.hashCode ^ lowerMhz.hashCode ^ upperMhz.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BandLimitDto &&
          runtimeType == other.runtimeType &&
          txEnabled == other.txEnabled &&
          lowerMhz == other.lowerMhz &&
          upperMhz == other.upperMhz;
}

/// Both bands' transmit limits, and which layout they were read from.
class BandLimitsDto {
  final BandLimitDto vhf;
  final BandLimitDto uhf;

  /// "old" or "new" -- informational; writes work it out again from the
  /// image rather than trusting a value that crossed the boundary.
  final String layout;

  const BandLimitsDto({
    required this.vhf,
    required this.uhf,
    required this.layout,
  });

  @override
  int get hashCode => vhf.hashCode ^ uhf.hashCode ^ layout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BandLimitsDto &&
          runtimeType == other.runtimeType &&
          vhf == other.vhf &&
          uhf == other.uhf &&
          layout == other.layout;
}

/// One block of a read or a write.
class CodeplugBlockDto {
  /// Address on the radio.
  final int addr;

  /// Offset into the flat image.
  final int imageOffset;
  final int len;

  const CodeplugBlockDto({
    required this.addr,
    required this.imageOffset,
    required this.len,
  });

  @override
  int get hashCode => addr.hashCode ^ imageOffset.hashCode ^ len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodeplugBlockDto &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          imageOffset == other.imageOffset &&
          len == other.len;
}

/// A step of the post-ident handshake.
class HandshakeStepDto {
  final Uint8List request;

  /// How many bytes the reply is. Dart reads exactly this many rather than
  /// guessing when the radio has finished talking.
  final int expectedReplyLen;

  const HandshakeStepDto({
    required this.request,
    required this.expectedReplyLen,
  });

  @override
  int get hashCode => request.hashCode ^ expectedReplyLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandshakeStepDto &&
          runtimeType == other.runtimeType &&
          request == other.request &&
          expectedReplyLen == other.expectedReplyLen;
}

/// One memory channel.
class RadioChannelDto {
  /// Slot number, from 1, as the radio counts them.
  final int slot;
  final String name;
  final int rxFreqHz;
  final int txFreqHz;
  final bool rxOnly;
  final ToneDto txTone;
  final ToneDto rxTone;
  final bool narrow;
  final bool lowPower;
  final bool skip;

  const RadioChannelDto({
    required this.slot,
    required this.name,
    required this.rxFreqHz,
    required this.txFreqHz,
    required this.rxOnly,
    required this.txTone,
    required this.rxTone,
    required this.narrow,
    required this.lowPower,
    required this.skip,
  });

  @override
  int get hashCode =>
      slot.hashCode ^
      name.hashCode ^
      rxFreqHz.hashCode ^
      txFreqHz.hashCode ^
      rxOnly.hashCode ^
      txTone.hashCode ^
      rxTone.hashCode ^
      narrow.hashCode ^
      lowPower.hashCode ^
      skip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadioChannelDto &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          name == other.name &&
          rxFreqHz == other.rxFreqHz &&
          txFreqHz == other.txFreqHz &&
          rxOnly == other.rxOnly &&
          txTone == other.txTone &&
          rxTone == other.rxTone &&
          narrow == other.narrow &&
          lowPower == other.lowPower &&
          skip == other.skip;
}

/// A radio this codec can program.
class RadioModelDto {
  final String id;
  final String displayName;

  /// The 16-byte string that puts the radio into programming mode.
  final Uint8List identMagic;
  final int imageLen;
  final int channelCount;
  final int nameLen;

  const RadioModelDto({
    required this.id,
    required this.displayName,
    required this.identMagic,
    required this.imageLen,
    required this.channelCount,
    required this.nameLen,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      identMagic.hashCode ^
      imageLen.hashCode ^
      channelCount.hashCode ^
      nameLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadioModelDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          identMagic == other.identMagic &&
          imageLen == other.imageLen &&
          channelCount == other.channelCount &&
          nameLen == other.nameLen;
}

/// A read that is not part of the image: made, checked, and set aside.
class ReadRequestDto {
  final int addr;
  final int len;

  const ReadRequestDto({required this.addr, required this.len});

  @override
  int get hashCode => addr.hashCode ^ len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReadRequestDto &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          len == other.len;
}

/// How a channel squelches, flattened for the boundary.
///
/// A tagged struct rather than a Rust enum with payloads: FRB renders those
/// as sealed classes that the Dart side then has to pattern-match, and this
/// crosses the boundary in both directions on every channel.
class ToneDto {
  /// "none", "ctcss" or "dcs".
  final String mode;

  /// CTCSS in tenths of a hertz.
  final int ctcssTenthHz;
  final int dcsCode;
  final bool dcsInverted;

  const ToneDto({
    required this.mode,
    required this.ctcssTenthHz,
    required this.dcsCode,
    required this.dcsInverted,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      ctcssTenthHz.hashCode ^
      dcsCode.hashCode ^
      dcsInverted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToneDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          ctcssTenthHz == other.ctcssTenthHz &&
          dcsCode == other.dcsCode &&
          dcsInverted == other.dcsInverted;
}

/// A radio of the older serial family.
class Uv5rModelDto {
  final String id;
  final String displayName;

  /// Ident magics, tried in order until one is acknowledged.
  final List<Uint8List> idents;

  const Uv5rModelDto({
    required this.id,
    required this.displayName,
    required this.idents,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ idents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uv5rModelDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          idents == other.idents;
}

/// What the reads after the ident found out about the radio.
class Uv5rProbeDto {
  final String firmware;

  /// Read the end of the aux block sixteen bytes at a time.
  final bool dropsByte;

  const Uv5rProbeDto({required this.firmware, required this.dropsByte});

  @override
  int get hashCode => firmware.hashCode ^ dropsByte.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uv5rProbeDto &&
          runtimeType == other.runtimeType &&
          firmware == other.firmware &&
          dropsByte == other.dropsByte;
}
