// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_channel`, `from_tone`, `model_or_error`, `none`, `to_channel`, `to_tone`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Every radio this codec can program.
Future<List<RadioModelDto>> radioModels() =>
    RustLib.instance.api.crateApiRadioApiRadioModels();

/// The string that puts this radio into programming mode.
Future<Uint8List> radioIdentMagic({required String modelId}) =>
    RustLib.instance.api.crateApiRadioApiRadioIdentMagic(modelId: modelId);

/// The byte the radio answers a good command with.
Future<int> radioAckByte() =>
    RustLib.instance.api.crateApiRadioApiRadioAckByte();

/// The handshake to run once the ident magic has been acknowledged.
Future<List<HandshakeStepDto>> radioHandshakeSteps() =>
    RustLib.instance.api.crateApiRadioApiRadioHandshakeSteps();

/// Every block of a full read, in order.
Future<List<CodeplugBlockDto>> radioReadPlan({required String modelId}) =>
    RustLib.instance.api.crateApiRadioApiRadioReadPlan(modelId: modelId);

/// Every block of a full write, in order.
///
/// `block_size` is a parameter because the radio's own Bluetooth takes
/// 0x80-byte writes while a cable takes 0x40 -- one codec, two callers.
Future<List<CodeplugBlockDto>> radioWritePlan({
  required String modelId,
  required int blockSize,
}) => RustLib.instance.api.crateApiRadioApiRadioWritePlan(
  modelId: modelId,
  blockSize: blockSize,
);

/// The write block size the radio's own Bluetooth expects.
Future<int> radioBleWriteBlockSize() =>
    RustLib.instance.api.crateApiRadioApiRadioBleWriteBlockSize();

/// The request that reads `len` bytes from `addr`.
Future<Uint8List> radioReadCommand({required int addr, required int len}) =>
    RustLib.instance.api.crateApiRadioApiRadioReadCommand(addr: addr, len: len);

/// How many bytes that read will answer with, header included.
///
/// Over Bluetooth the reply arrives in ~20-byte notifications; this is how
/// the Dart side tells "still arriving" from "done".
Future<int> radioExpectedReplyLen({required int len}) =>
    RustLib.instance.api.crateApiRadioApiRadioExpectedReplyLen(len: len);

/// The payload of a read reply, substitution undone and header checked.
Future<Uint8List> radioParseReadReply({
  required List<int> reply,
  required int addr,
  required int len,
}) => RustLib.instance.api.crateApiRadioApiRadioParseReadReply(
  reply: reply,
  addr: addr,
  len: len,
);

/// The request that writes `data` to `addr`.
Future<Uint8List> radioWriteCommand({
  required int addr,
  required List<int> data,
}) => RustLib.instance.api.crateApiRadioApiRadioWriteCommand(
  addr: addr,
  data: data,
);

/// Whether a reply is the radio's acknowledgement.
Future<bool> radioIsAck({required List<int> reply}) =>
    RustLib.instance.api.crateApiRadioApiRadioIsAck(reply: reply);

/// The channels in a codeplug image. Empty slots are omitted; each channel
/// carries the slot it came from.
Future<List<RadioChannelDto>> radioDecodeChannels({
  required List<int> image,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioDecodeChannels(
  image: image,
  modelId: modelId,
);

/// A copy of `image` with `channels` written from slot 1 up and the rest of
/// the slots cleared.
///
/// Everything outside the channel records survives: the settings, the DTMF
/// codes, the parts of each record this codec does not model.
Future<Uint8List> radioEncodeChannels({
  required List<int> image,
  required List<RadioChannelDto> channels,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioEncodeChannels(
  image: image,
  channels: channels,
  modelId: modelId,
);

/// Whether an image is the size this model reads back.
///
/// Checked before a write, because an image of the wrong length means the
/// read that produced it was cut short, and writing it back would leave the
/// radio holding half a codeplug.
Future<bool> radioImageIsComplete({
  required int imageLen,
  required String modelId,
}) => RustLib.instance.api.crateApiRadioApiRadioImageIsComplete(
  imageLen: imageLen,
  modelId: modelId,
);

/// One block of a read or a write.
class CodeplugBlockDto {
  /// Address on the radio.
  final int addr;

  /// Offset into the flat image.
  final int imageOffset;
  final int len;

  const CodeplugBlockDto({
    required this.addr,
    required this.imageOffset,
    required this.len,
  });

  @override
  int get hashCode => addr.hashCode ^ imageOffset.hashCode ^ len.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodeplugBlockDto &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          imageOffset == other.imageOffset &&
          len == other.len;
}

/// A step of the post-ident handshake.
class HandshakeStepDto {
  final Uint8List request;

  /// How many bytes the reply is. Dart reads exactly this many rather than
  /// guessing when the radio has finished talking.
  final int expectedReplyLen;

  const HandshakeStepDto({
    required this.request,
    required this.expectedReplyLen,
  });

  @override
  int get hashCode => request.hashCode ^ expectedReplyLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandshakeStepDto &&
          runtimeType == other.runtimeType &&
          request == other.request &&
          expectedReplyLen == other.expectedReplyLen;
}

/// One memory channel.
class RadioChannelDto {
  /// Slot number, from 1, as the radio counts them.
  final int slot;
  final String name;
  final int rxFreqHz;
  final int txFreqHz;
  final bool rxOnly;
  final ToneDto txTone;
  final ToneDto rxTone;
  final bool narrow;
  final bool lowPower;
  final bool skip;

  const RadioChannelDto({
    required this.slot,
    required this.name,
    required this.rxFreqHz,
    required this.txFreqHz,
    required this.rxOnly,
    required this.txTone,
    required this.rxTone,
    required this.narrow,
    required this.lowPower,
    required this.skip,
  });

  @override
  int get hashCode =>
      slot.hashCode ^
      name.hashCode ^
      rxFreqHz.hashCode ^
      txFreqHz.hashCode ^
      rxOnly.hashCode ^
      txTone.hashCode ^
      rxTone.hashCode ^
      narrow.hashCode ^
      lowPower.hashCode ^
      skip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadioChannelDto &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          name == other.name &&
          rxFreqHz == other.rxFreqHz &&
          txFreqHz == other.txFreqHz &&
          rxOnly == other.rxOnly &&
          txTone == other.txTone &&
          rxTone == other.rxTone &&
          narrow == other.narrow &&
          lowPower == other.lowPower &&
          skip == other.skip;
}

/// A radio this codec can program.
class RadioModelDto {
  final String id;
  final String displayName;

  /// The 16-byte string that puts the radio into programming mode.
  final Uint8List identMagic;
  final int imageLen;
  final int channelCount;
  final int nameLen;

  const RadioModelDto({
    required this.id,
    required this.displayName,
    required this.identMagic,
    required this.imageLen,
    required this.channelCount,
    required this.nameLen,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      identMagic.hashCode ^
      imageLen.hashCode ^
      channelCount.hashCode ^
      nameLen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadioModelDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          identMagic == other.identMagic &&
          imageLen == other.imageLen &&
          channelCount == other.channelCount &&
          nameLen == other.nameLen;
}

/// How a channel squelches, flattened for the boundary.
///
/// A tagged struct rather than a Rust enum with payloads: FRB renders those
/// as sealed classes that the Dart side then has to pattern-match, and this
/// crosses the boundary in both directions on every channel.
class ToneDto {
  /// "none", "ctcss" or "dcs".
  final String mode;

  /// CTCSS in tenths of a hertz.
  final int ctcssTenthHz;
  final int dcsCode;
  final bool dcsInverted;

  const ToneDto({
    required this.mode,
    required this.ctcssTenthHz,
    required this.dcsCode,
    required this.dcsInverted,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      ctcssTenthHz.hashCode ^
      dcsCode.hashCode ^
      dcsInverted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToneDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          ctcssTenthHz == other.ctcssTenthHz &&
          dcsCode == other.dcsCode &&
          dcsInverted == other.dcsInverted;
}
