// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<bool> serialPortsSupported() =>
    RustLib.instance.api.crateApiSerialApiSerialPortsSupported();

/// The serial ports present now.
Future<List<SerialPortInfoDto>> serialListPorts() =>
    RustLib.instance.api.crateApiSerialApiSerialListPorts();

/// Open `path` at `baud_rate`, 8N1, no flow control, DTR and RTS raised.
/// Answers the handle the other calls take.
Future<int> serialOpen({required String path, required int baudRate}) => RustLib
    .instance
    .api
    .crateApiSerialApiSerialOpen(path: path, baudRate: baudRate);

Future<void> serialWrite({required int handle, required List<int> data}) =>
    RustLib.instance.api.crateApiSerialApiSerialWrite(
      handle: handle,
      data: data,
    );

/// Read exactly `len` bytes, giving up after `timeout_ms`.
///
/// Blocks, which is what a non-sync bridge function is for: it runs on the
/// bridge's worker pool, never on the Dart isolate.
Future<SerialReadDto> serialReadExact({
  required int handle,
  required int len,
  required int timeoutMs,
}) => RustLib.instance.api.crateApiSerialApiSerialReadExact(
  handle: handle,
  len: len,
  timeoutMs: timeoutMs,
);

/// Forget anything received and not yet read.
Future<void> serialDiscardInput({required int handle}) =>
    RustLib.instance.api.crateApiSerialApiSerialDiscardInput(handle: handle);

/// Close the port. Closing it twice is harmless.
Future<void> serialClose({required int handle}) =>
    RustLib.instance.api.crateApiSerialApiSerialClose(handle: handle);

/// A serial port present on this machine.
class SerialPortInfoDto {
  /// What the port is opened by: `/dev/ttyUSB0`, `/dev/cu.usbserial-110`.
  final String path;
  final int? vendorId;
  final int? productId;
  final String? manufacturer;
  final String? product;

  const SerialPortInfoDto({
    required this.path,
    this.vendorId,
    this.productId,
    this.manufacturer,
    this.product,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      vendorId.hashCode ^
      productId.hashCode ^
      manufacturer.hashCode ^
      product.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerialPortInfoDto &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          manufacturer == other.manufacturer &&
          product == other.product;
}

/// What a read produced.
///
/// A timeout is an answer, not an error: it carries whatever did arrive, and
/// Dart turns it into the same `TimeoutException` its other links raise
/// instead of parsing one out of an error message.
class SerialReadDto {
  final Uint8List data;
  final bool timedOut;

  const SerialReadDto({required this.data, required this.timedOut});

  @override
  int get hashCode => data.hashCode ^ timedOut.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SerialReadDto &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          timedOut == other.timedOut;
}
