// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: inference_failure_on_instance_creation

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../spec/types.dart';
import 'device_api.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_hex`, `entry_at`, `parse_chunk`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CatalogueSpec`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Parse a spec and keep it, returning the handle that addresses it.
///
/// The YAML crosses the boundary once, here. Every later call about this
/// spec sends a pointer.
Future<LoadedSpec> loadSpec({required String yaml}) =>
    RustLib.instance.api.crateApiSpecHandleLoadSpec(yaml: yaml);

/// An empty catalogue, ready for [`CatalogueHandle::add_specs`].
Future<CatalogueHandle> newCatalogue() =>
    RustLib.instance.api.crateApiSpecHandleNewCatalogue();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CatalogueHandle>>
abstract class CatalogueHandle implements RustOpaqueInterface {
  /// Parse and append a chunk of the catalogue, in the order given.
  ///
  /// Returns the specs in this chunk that did not parse; the rest are
  /// appended. A spec that fails is skipped rather than failing the whole
  /// catalogue, which is what the Dart loader did before and why one bad
  /// vendored spec cannot take matching out.
  ///
  /// `keys` and `yamls` are parallel lists. A length mismatch is a caller
  /// bug, so it is an error rather than a silent truncation.
  Future<List<SpecLoadFailureDto>> addSpecs({
    required List<String> keys,
    required List<String> yamls,
  });

  /// The full DTO of the spec at `index`.
  Future<DeviceSpecDto> dtoAt({required int index});

  /// Every entry's light projection, in catalogue order.
  Future<List<CatalogueEntryDto>> entries();

  /// Match every spec in the catalogue against a device we are already
  /// connected to, by advertised name and discovered GATT services.
  ///
  /// Two strings in, matched indices out. The by-value twin
  /// (`match_device_to_spec`) shares the axes rule through
  /// [`match_connected_device`], so the two agree by construction.
  Future<List<CatalogueMatchDto>> matchDevice({
    required String deviceName,
    required List<String> serviceUuids,
  });

  /// A handle to the spec at `index`, sharing the catalogue's parse.
  ///
  /// This is how a screen goes from "spec 41 matched" to driving the
  /// device: no re-parse, and no YAML crossing in either direction.
  Future<LoadedSpec> specAt({required int index});

  /// Every UDP discovery probe the catalogue declares.
  ///
  /// The scan service asks this once and sends what comes back, instead of
  /// holding a constant and a transport per vendor. A spec whose probe is
  /// unusable — no port, or `probe_hex` that is not hex — is left out rather
  /// than reported: discovery is best-effort by nature, and one bad block
  /// should cost that device, not the scan.
  Future<List<UdpProbeDto>> udpBroadcastProbes();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LoadedSpec>>
abstract class LoadedSpec implements RustOpaqueInterface {
  /// Decode raw bytes from a BLE read or notification into named values.
  ///
  /// The hot one: a notify-driven sensor tile lands here several times a
  /// second, and this is the call that used to carry the spec with it.
  Future<List<DecodedValueDto>> decodeValue({
    String? serviceUuid,
    required String charUuid,
    required List<int> bytes,
  });

  /// The full DTO for this spec — services, entities, commands and all.
  ///
  /// Fetched for the specs a screen actually renders, not for the whole
  /// catalogue: decoding 203 of these was the UI-isolate stall this module
  /// exists to remove.
  Future<DeviceSpecDto> dto();

  /// Encode a named command into the bytes for a BLE write.
  Future<Uint8List> encodeCommand({
    String? serviceUuid,
    required String charUuid,
    required String commandName,
    required Map<String, double> params,
  });

  /// Encode a setpoint the user picked, in decoded units, into the write
  /// that applies it.
  Future<EntityWriteDto> encodeEntityValue({
    required String entityName,
    required double value,
  });

  /// Enumerate the children an instanced entity's state reply carries.
  Future<List<NetworkInstanceDto>> listNetworkInstances({
    required String entityName,
    required String stateReply,
  });

  /// Decode one entity's state from the name→value pairs a state call
  /// returned.
  Future<NetworkReadingDto?> readNetworkEntity({
    required String entityName,
    required Map<String, String> returned,
  });

  /// Read one child's roles out of an instanced entity's state reply.
  Future<List<NetworkRoleReadingDto>> readNetworkInstance({
    required String entityName,
    required String stateReply,
    required String instanceId,
  });

  /// Render the HTTP request that reads a state command's values — the
  /// other repeated caller, on a 4-second poll per network device.
  Future<HttpRequestDto> renderNetworkHttpStateRequest({
    required String stateCommand,
    required Map<String, String> values,
  });

  /// Render the argument-less SOAP request that reads a state command's
  /// values.
  Future<SoapRequestDto> renderNetworkStateRequest({
    required String stateCommand,
  });
}

/// One catalogue entry as Dart sees it: everything the scan, adopt, group and
/// network paths ask of a spec they are not rendering, and nothing else.
///
/// This is the projection that replaced 203 full [`DeviceSpecDto`]s on the
/// startup path. A screen that actually renders a spec asks for its handle
/// (and its DTO) by index.
class CatalogueEntryDto {
  /// Position in the catalogue — the index every other call here takes.
  final int index;

  /// The key the caller filed this spec under.
  final String key;

  /// The identifying projection the scan matchers already take by value.
  final SpecIdentityDto identity;

  /// `device.protocol_handler`, which the adopt and Rabbit Air paths select
  /// specs by.
  final String? protocolHandler;

  /// UUIDs of the GATT services the spec declares, as declared. The
  /// post-connect ranking drops a name-only match that none of these
  /// corroborates, and it must be able to ask that without the whole spec.
  final List<String> gattServiceUuids;

  const CatalogueEntryDto({
    required this.index,
    required this.key,
    required this.identity,
    this.protocolHandler,
    required this.gattServiceUuids,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      key.hashCode ^
      identity.hashCode ^
      protocolHandler.hashCode ^
      gattServiceUuids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogueEntryDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          key == other.key &&
          identity == other.identity &&
          protocolHandler == other.protocolHandler &&
          gattServiceUuids == other.gattServiceUuids;
}

/// One catalogue entry's match against a connected device.
///
/// Indices, not specs: this is what [`CatalogueHandle::match_device`] returns
/// instead of the 203 `DeviceSpecDto`s that went in and the matched ones that
/// came back.
class CatalogueMatchDto {
  /// Index into the catalogue.
  final int index;
  final bool matchedByNamePrefix;
  final MatchConfidence confidence;
  final List<String> matchedServiceUuids;

  const CatalogueMatchDto({
    required this.index,
    required this.matchedByNamePrefix,
    required this.confidence,
    required this.matchedServiceUuids,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      matchedByNamePrefix.hashCode ^
      confidence.hashCode ^
      matchedServiceUuids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CatalogueMatchDto &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          matchedByNamePrefix == other.matchedByNamePrefix &&
          confidence == other.confidence &&
          matchedServiceUuids == other.matchedServiceUuids;
}

/// A spec the catalogue could not parse, named so the load can report it
/// rather than silently shrinking.
class SpecLoadFailureDto {
  /// The key the caller filed the spec under (an asset path, or
  /// `pack:<name>/<file>`).
  final String key;

  /// What the parser said.
  final String message;

  const SpecLoadFailureDto({required this.key, required this.message});

  @override
  int get hashCode => key.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpecLoadFailureDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          message == other.message;
}

/// One field a UDP reply is read for, with its dialect split out.
class UdpIdentityFieldDto {
  /// `json`, `tlv`, `csv` or `payload` — how to read [`Self::path`].
  final String dialect;

  /// What to read, in that dialect: a dotted JSON path, a TLV field name, a
  /// CSV column index, or empty for the payload itself.
  final String path;

  /// What to call the value once read.
  final String name;

  const UdpIdentityFieldDto({
    required this.dialect,
    required this.path,
    required this.name,
  });

  @override
  int get hashCode => dialect.hashCode ^ path.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UdpIdentityFieldDto &&
          runtimeType == other.runtimeType &&
          dialect == other.dialect &&
          path == other.path &&
          name == other.name;
}

/// One UDP discovery probe a spec declares, ready for a caller to send.
///
/// Thirteen bundled specs mention `udp_broadcast` and ten declare a usable
/// block; the app executed none of them, carrying four of the payloads as Dart
/// constants beside a hand-written transport each and simply not finding the
/// devices the other specs describe (SPECS_TO_FIX.md S-10). The hex is decoded
/// here rather than in Dart so a malformed `probe_hex` is one spec that drops
/// out of discovery instead of an exception in the middle of a scan.
class UdpProbeDto {
  /// The catalogue key of the spec that declared this probe, so a reply can
  /// be attributed to the device it belongs to.
  final String specKey;

  /// Index into the catalogue, for callers that then want the whole spec.
  final int index;

  /// What the spec calls this device, for the row a reply becomes.
  final String displayName;

  /// The port to send to, and for a passive probe the port to listen on.
  final int port;

  /// Where to send it. Usually the v4 broadcast address; the Aqara hub names
  /// a multicast group instead, which a caller must join rather than
  /// broadcast to.
  final String broadcastAddress;

  /// The bytes to send, decoded from `probe_hex`. Empty when the spec
  /// declares none, which is only meaningful together with [`Self::passive_ok`].
  final Uint8List probe;

  /// The device announces itself unprompted, so a caller that only listens
  /// still finds it. Tuya and Synology are found this way.
  final bool passiveOk;

  /// How to read a reply, as the spec names it (`json`, `tlv`, …). Advisory:
  /// the app's own parsers are keyed off the spec, not off this string.
  final String? responseFormat;

  /// Fields that identify the answering device across scans.
  final List<UdpIdentityFieldDto> stableKeys;

  /// The field to show the user, when the spec names one.
  final UdpIdentityFieldDto? displayField;

  const UdpProbeDto({
    required this.specKey,
    required this.index,
    required this.displayName,
    required this.port,
    required this.broadcastAddress,
    required this.probe,
    required this.passiveOk,
    this.responseFormat,
    required this.stableKeys,
    this.displayField,
  });

  @override
  int get hashCode =>
      specKey.hashCode ^
      index.hashCode ^
      displayName.hashCode ^
      port.hashCode ^
      broadcastAddress.hashCode ^
      probe.hashCode ^
      passiveOk.hashCode ^
      responseFormat.hashCode ^
      stableKeys.hashCode ^
      displayField.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UdpProbeDto &&
          runtimeType == other.runtimeType &&
          specKey == other.specKey &&
          index == other.index &&
          displayName == other.displayName &&
          port == other.port &&
          broadcastAddress == other.broadcastAddress &&
          probe == other.probe &&
          passiveOk == other.passiveOk &&
          responseFormat == other.responseFormat &&
          stableKeys == other.stableKeys &&
          displayField == other.displayField;
}
